### ISSUE TITLE
Add support for claimRef for persistent kubernetes volume

### ISSUE THREAD

**Issue by dvulpe** [hashicorp/terraform-provider-kubernetes#1004]
### Description

Having persistent volumes in Kubernetes is a bit controversial when the kubernetes nodes span multiple availability zones. There are some tricks to ensure the spread of volumes across availability zones in Kubernetes, but they don't offer strong guarantees.

We would like to statically manage the kubernetes PVs using terraform, but with the cloud-specific provider (aws for example). This works great, as we can control the lifecycle of the volumes completely outside of Kubernetes which gives us predictability.

To fully enable us to statically manage the volumes outside we need to create the PVs inside k8s. This is straight forward to achieve with this Kubernetes provider - except an important detail - the [`claimRef`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#binding) attributes which tie a PersistentVolume to a PersistentVolumeClaim. 
Adding support to modify `claimRef` would allow us to use the terraform kubernetes provider to create the kubernetes PersistentVolume objects - we currently render yaml templates like the one below and apply them with kubectl.

Here is an example of the k8s manifest containing claimRef:
```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-data-5
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: kafka
    name: datadir-0-kafka-cp-kafka-5
  awsElasticBlockStore:
    volumeID: vol-0b8874ec0466d3703
    fsType: xfs
    readOnly: false
  volumeMode: Filesystem
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
                - eu-west-1c
            - key: failure-domain.beta.kubernetes.io/region
              operator: In
              values:
                - eu-west-1
```
### Potential Terraform Configuration
```hcl
resource "kubernetes_persistent_volume" "pv" {

  metadata {
    name = "kafka-data-5"
  }
  spec {
    access_modes                     = ["ReadWriteOnce"]
    capacity                         = {
      storage = "${aws_ebs_volume.kafka_data.size}Gi"
    }
    persistent_volume_reclaim_policy = "Retain"
    
    claim_ref = {
       namespace = "kafka"
       name = "datadir-0-kafka-cp-kafka-5"
    }

    persistent_volume_source {
      aws_elastic_block_store {
        fs_type   = "xfs"
        volume_id = aws_ebs_volume.kafka_data.id
      }
    }
    node_affinity {
      required {
        node_selector_term {
          match_expressions {
            key      = "failure-domain.beta.kubernetes.io/zone"
            operator = "In"
            values   = ["eu-west-1c"]
          }
          match_expressions {
            key      = "failure-domain.beta.kubernetes.io/region"
            operator = "In"
            values   = ["eu-west-1"]
          }
        }
      }
    }
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
