### ISSUE TITLE
config_context ignore

### ISSUE THREAD

**Issue by Djabx** [hashicorp/terraform-provider-kubernetes#1018]
### Terraform Version and Provider Version

Terraform: 0.12.29
+ provider.google v3.40.0
+ provider.google-beta v3.40.0
+ provider.kubernetes v1.13.2

### Affected Resource(s)

- provider

### Terraform Configuration Files
```hcl
resource "null_resource" "cluster" {
  provisioner "local-exec" {
    command = "gcloud container clusters get-credentials ${local.cluster_name} --project=${local.project_id} --zone=${local.zones[0]}"
  }
}

provider "kubernetes" {
  config_context  = "gke_${local.project_id}_${local.zones[0]}_${local.cluster_name}"
  load_config_file       = false

  alias = "cluster"
}
```

### Expected Behavior
I should connect to my cluster

### Actual Behavior

The context file is created like this:

```yaml
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://1.1.1.1
  name: gke_project_europe-west1-b_cluster-name
[...]
- name: gke_project_europe-west1-b_cluster-name
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib64/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

But when I do my `terraform apply` I've got this output:

```shell
Error: Post "http://localhost/api/v1/namespaces/default/serviceaccounts": dial tcp [::1]:80: connect: connection refused
```

The URL does not seem to be changed.

### References

- #813 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
