### ISSUE TITLE
Add path_type to kubernetes_ingress

### ISSUE THREAD

**Issue by zolty** [hashicorp/terraform-provider-kubernetes#1023]
### Description

I am fairly new to kubernetes so I can't suggest how this can be done but we'd really like the ability to specify path_type as part of rule within a kubernetes_ingress. 

### Potential Terraform Configuration

In Yaml this would look like this:
```yaml

- path: /api/app.api
        pathType: Prefix
        backend:
          serviceName: appapi
          servicePort: 80


```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
