### ISSUE TITLE
Add the ability to define scopeSelector in resourceQuota

### ISSUE THREAD

**Issue by avkudryashov** [hashicorp/terraform-provider-kubernetes#1157]
### Description

The ResourceQuota resource has the ability to define for which priorityClass the quota applies.
```yaml
    scopeSelector:
      matchExpressions:
      - operator : In
        scopeName: PriorityClass
        values: ["medium"]
```
This feature is missing in kubernetes_resource_quota resource

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
