### ISSUE TITLE
namespace defaults to "default" even if config file directly mentions namespace

### ISSUE THREAD

**Issue by bfanyuk** [hashicorp/terraform-provider-kubernetes#1231]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.8
Kubernetes provider version: 2.0.3
Kubernetes version: 1.19
```

### Affected Resource(s)
Any kubernetes_*** resource 

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_path    = "~/.kube/config-production"
  config_context = "production"
}

resource "kubernetes_config_map" "my_config_map" {
  metadata {
    name = "my-config-map"
  }
}
```

### ~/.kube/config-production
```yaml
apiVersion: v1
kind: Config
clusters:
- name: "production"
  cluster:
    server: "xxx"

users:
- name: "production"
  user:
    token: "xxx"

contexts:
- name: "production"
  context:
    user: "production"
    cluster: "production"
    namespace: xxx

current-context: "production"


```

### terraform plan 
```
Terraform will perform the following actions:

  # kubernetes_config_map.my_config_map will be created
  + resource "kubernetes_config_map" "my_config_map" {
      + id = (known after apply)

      + metadata {
          + generation       = (known after apply)
          + name             = "my-config-map"
          + namespace        = "default"
          + resource_version = (known after apply)
          + self_link        = (known after apply)
          + uid              = (known after apply)
        }
    }
```

### Expected Behavior
namespace is not explicitly defined, as a result namespace from the config file is applied 

### Actual Behavior
namespace is set to "default"  

### Important Factoids
This is also a default behavior for kubectl.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
