### ISSUE TITLE
persistent volume claim: support data source 

### ISSUE THREAD

**Issue by bfanyuk** [hashicorp/terraform-provider-kubernetes#1232]
### Description

Currently **kubernetes_persistent_volume_claim** does not allow to specify data source.
This prevents us from using terraform to automate volume backups.

### Potential Terraform Configuration

```hcl
resource "kubernetes_persistent_volume_claim" "default" {
  metadata {
    name = "my-pvc-clone"
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "1Gi"
      }
    }
    data_source {
      persistent_volume_claim {
        claim_name = "my-pvc-original"
      }
    }
  }
}
```

### Сorresponding kubectl manifest

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-clone
spec:
  dataSource:
    kind: PersistentVolumeClaim
    name: my-pvc-original
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
