### ISSUE TITLE
HCL2 no dot in key allowed vs Yaml - preventing secret tls creation.

### ISSUE THREAD

**Issue by styk-tv** [hashicorp/terraform-provider-kubernetes#1311]
```
Terraform version: v1.0.0
Kubernetes provider version: hashicorp/kubernetes v2.3.2
```

HLC2 Example below as per kubernetes:
```
resource "kubernetes_secret" "tls-secret" {
  type  = "kubernetes.io/tls"

  metadata {
    name      = "foo-secret"
  }

  data {
    "tls.crt" = "${var.site_certificate}"
    "tls.key" = "${var.site_certificate_key}"
  }
}
```

Above cannot be processed by TF:
1. with quotes: `Error: Invalid argument name. Argument names must not be quoted`
2. without quotes: 'Error: Argument or block definition required. │An argument or block definition is required here. To set an argument, use the equals sign "=" to introduce the argument value.`

YAML - Kubernetes documentation example:
https://kubernetes.io/docs/concepts/configuration/secret/#tls-secrets
```
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
type: kubernetes.io/tls
data:
  # the data is abbreviated in this example
  tls.crt: |
        MIIC2DCCAcCgAwIBAgIBATANBgkqh ...
  tls.key: |
        MIIEpgIBAAKCAQEA7yn3bRHQ5FHMQ ...
```

No example for `type  = "kubernetes.io/tls"` - probably because invalid - a note here would be appreciated
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/secret

Probably not the smartest idea on part of kubernetes maintainers to allow a key with a dot but it seems to be allowed in Yaml. What do you do in such cases? Any help would be appreciated. 

Related: https://github.com/hashicorp/nomad/issues/9701
