### ISSUE TITLE
Update networking version to networking.k8s.io/v1 for K8s cluster v1.19+

### ISSUE THREAD

**Issue by Sudharma** [hashicorp/terraform-provider-kubernetes#1319]
From kubernetes version v1.19 onwards the api version for Ingress is GA and it is deprecated as of now. However after kubernetes v1.22, `networking.k8s.io/v1beta1` will be removed. 

Reference : https://kubernetes.io/docs/concepts/services-networking/ingress/#the-ingress-resource

```
Terraform version: 1.0.1
Kubernetes provider version:  1.13.3
Kubernetes version: 1.20
```

### Affected Resource(s)
- kubernetes_ingress

### Expected Behavior
For versions of K8s > v1.19+ the new api version (`networking.k8s.io/v1`) should be used. Also there is change in the syntax of the yaml for backend service name and port as below

```
rules:
  - http:
      paths:
      - path: /testpath
        pathType: Prefix
        backend:
          service:
            name: test
            port:
              number: 80
```

### Actual Behavior
What actually happened?

### References
https://github.com/kubernetes/kubernetes/issues/94761
