### ISSUE TITLE
FrontendConfig resource for HTTP to HTTPS redirection (& SSL policies)

### ISSUE THREAD

**Issue by pvanliefland** [hashicorp/terraform-provider-kubernetes#1326]
### Description

GKE has finally provided a simple way to handle HTTP to HTTPS redirection, using [FrontendConfig](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect):

```yaml
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: my-frontend-config
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: RESPONSE_CODE
```

It seems that SSL policies can be configured using `FrontendConfig` as well but I haven't tried it myself.

### Potential Terraform Configuration

It would be great to have something like this:

```hcl
resource "kubernetes_frontend_config" "example" {
  metadata {
    name = "my-frontend-config"
  }
  spec {
    redirectToHttps {
      enabled = true
      responseCodeName = "MOVED_PERMANENTLY_DEFAULT"
    }
  }
}
```

### References

https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#https_redirect

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
