### ISSUE TITLE
kubernetes_manifest spec.image.application regexp doesn't account for custom registries

### ISSUE THREAD

**Issue by Quintasan** [hashicorp/terraform-provider-kubernetes#1375]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.0.4
Kubernetes provider version: 2.4.1
Kubernetes version: whatever GKE has
```

### Affected Resource(s)

- `kubernetes_manifest`

### Terraform Configuration Files
I got the following resource by using https://github.com/sl1pm4t/k2tf
on the following YAML

```yaml
---
apiVersion: platform.confluent.io/v1beta1
kind: Connect
metadata:
  name: connect
  namespace: confluent
spec:
  replicas: 1
  internalTopicReplicationFactor: 1
  podTemplate:
    serviceAccountName: gitlab-docker-service-account
    envVars:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /mnt/secrets/google-application-credentials/gcp-key.json
  image:
    application: registry.gitlab.com/somenamespace/someproject/cp-init-container-operator:latest
    init: confluentinc/cp-init-container-operator:6.1.0.0
  mountedSecrets:
    - secretRef: google-application-credentials
      keyItems:
        - key: gcp
          path: gcp-key.json
  dependencies:
    kafka:
      bootstrapEndpoint: kafka:9071
  externalAccess:
    type: loadBalancer
    loadBalancer:
      domain: somedomain.tld
```

Result

```hcl
resource "kubernetes_manifest" "connect_confluent_connect" {
  manifest = {
    "apiVersion" = "platform.confluent.io/v1beta1"
    "kind"       = "Connect"
    "metadata" = {
      "name"      = "connect"
      "namespace" = "confluent"
    }
    "spec" = {
      "dependencies" = {
        "kafka" = {
          "bootstrapEndpoint" = "kafka:9071"
        }
      }
      "externalAccess" = {
        "loadBalancer" = {
          "domain" = "somedomain.tld"
        }
        "type" = "loadBalancer"
      }
      "image" = {
        "application" = "registry.gitlab.com/${var.gitlab_project_namespace}/${var.gitlab_project_name}"
        "init"        = "confluentinc/cp-init-container-operator:6.1.0.0"
      }
      "internalTopicReplicationFactor" = 1
      "mountedSecrets" = [
        {
          "keyItems" = [
            {
              "key"  = "gcp"
              "path" = "gcp-key.json"
            },
          ]
          "secretRef" = "google-application-credentials"
        },
      ]
      "podTemplate" = {
        "envVars" = [
          {
            "name"  = "GOOGLE_APPLICATION_CREDENTIALS"
            "value" = "/mnt/secrets/google-application-credentials/gcp-key.json"
          },
        ]
        "serviceAccountName" = "gitlab-docker-service-account"
      }
      "replicas" = 1
    }
  }
}

```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
I expect this resource to work with custom registry URL

### Actual Behavior
It doesn't work

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
