### ISSUE TITLE
kubernetes_manifest resource warns OpenAPI schema not recognised and updates will force recreation

### ISSUE THREAD

**Issue by Doug-North** [hashicorp/terraform-provider-kubernetes#1382]
### Terraform Version, Provider Version and Kubernetes Version
```
Terraform v1.0.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.55.0
+ provider registry.terraform.io/hashicorp/helm v2.2.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/vault v2.23.0
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
```
│ Warning: This custom resource does not have an associated OpenAPI schema.
│ 
│   with kubernetes_manifest.monese_dev_kafka_users["test-user"],
│   on new-kafka-users.tf line 50, in resource "kubernetes_manifest" "kafka_users":
│   50: resource "kubernetes_manifest" "kafka_users" {
│ 
│ We could not find an OpenAPI schema for this custom resource. Updates to
│ this resource will cause a forced replacement.
│ 
│ (and one more similar warning elsewhere)
╵
````

### Steps to Reproduce
1. `terraform apply` -->

### Expected Behavior
No warning - and for the OpenApi schema defined in CRD to be recognised 

### Actual Behavior
Warning, and a resource that for me is not usable.

### Important Factoids
- Issue was on previous "kubernetes-alpha" provider too.
- CRD created by Strimzi v0.22.0
- CRD uses OpenApi Schema 

### References
- https://github.com/hashicorp/terraform-provider-kubernetes-alpha/issues/243

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ls-sajad-sameti** [comment]
any news on this issue? we are facing the same problem with IstioOperator CRD.

**Comment by warwick-mitchell1** [comment]
@ls-sajad-sameti  I'm pretty sure this is an issue with Istio not providing the Schema in the CRD correctly.
Unfortunately had no luck in asking the Istio team to add: https://github.com/istio/istio/issues/33535

**Comment by scbay** [comment]
We experienced the same with Longhorn or it's CRD altough it is installed in our cluster we get this warning.
Anyone working on this issue and can share some status?

**Comment by jbg** [comment]
@scbay It's not about the CRD being missing from your cluster (if it was, you would not be able to create the object at all). You receive this warning because some CRD authors unfortunately leave the schema unspecified in the CRD definition (so it's basically just a freeform object), which prevents validation of the object you create with `kubernetes_manifest` and prevents proper diffing on changes (so the object has to be replaced whenever it is changed).

The "proper" solution is to ask your vendor to please fix their CRDs to follow best practices. Unfortunately many vendors can't or won't produce good quality CRDs.

If the warning is accompanied by some other problem (@Doug-North said "Actual behaviour: Warning, and a resource that for me is not usable" but didn't expand on what "not usable" meant), the other problem is likely unrelated to the warning.

I'd love if there was a way to silence the warning. We have some vendor CRDs which have this problem and the persistent warning is annoying. Something like `kubectl_manifest`'s `force_new = true` so that you could explicitly opt-in to the replace-on-change behaviour which could also silence this warning.

**Comment by ecerulm** [comment]
I have the same problem with the `eniconfigs.crd.k8s.amazonaws.com` CRDs, terraform complains  about `This custom resource does not have an associated OpenAPI schema`, but the CRDs seems to have an `openAPIV3Schema` see source code [here](https://github.com/aws/amazon-vpc-cni-k8s/blob/e65d256c6dfa3e2dc318c6319b3c1a70addfa764/config/master/aws-k8s-cni.yaml#L33). 

```
# Source: aws-vpc-cni/templates/customresourcedefinition.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: eniconfigs.crd.k8s.amazonaws.com
  labels:
    app.kubernetes.io/name: aws-node
    app.kubernetes.io/instance: aws-vpc-cni
    k8s-app: aws-node
    app.kubernetes.io/version: "v1.11.4"
spec:
  scope: Cluster
  group: crd.k8s.amazonaws.com
  preserveUnknownFields: false
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
  names:
    plural: eniconfigs
    singular: eniconfig
    kind: ENIConfig
```

I'm not familiar with Open API Schema so I don't know what's wrong with this openAPIV3Schema, **is terraform right or wrong when it says that there is no OpenAPI schema for this CRD**?

**Comment by jbg** [comment]
There is no schema in that CRD.

**Comment by ecerulm** [comment]
The CRD has a '.spec.versions[0].schema.openAPIV3Schema', is not that the schema? 
I mean the 

```
   schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
```

seems like the one of the examples that they give in the [Kubernetes Documentation for OpenAPI v3 validation schema](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#controlling-pruning). 

I though that "openAPIV3Schema"  meant that  the value must be an object, and nothing else. Do you mean that is not right kind of schema? 

Is there any good example of an actual CRD that can be managed with `kubernetes_manifest` so that I can look to the source code and see what is an actual valid "OpenAPI schema"?
