### ISSUE TITLE
Unmarshaling unknown values is not supported

### ISSUE THREAD

**Issue by flvndh** [hashicorp/terraform-provider-kubernetes#1402]
### Terraform Version, Provider Version and Kubernetes Version
```
> tf version
Terraform v1.0.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/kubernetes v2.4.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
```

### Affected Resource(s)
- `kubernetes_manifest`

### Terraform Configuration Files
```hcl
resource "kubernetes_namespace" "this" {
  metadata {
    name = var.kubernetes_namespace
  }
}

data "template_file" "persistent_volume_manifest" {
  template = file("assets/persistent-volume.yaml")
  vars = {
    name      = var.persistent_volume_name
    host_path = var.host_path
  }
}

resource "kubernetes_manifest" "persistent_volume" {
  manifest = yamldecode(data.template_file.persistent_volume_manifest.rendered)
}

data "template_file" "persistent_volume_claim_manifest" {
  template = file("assets/persistent-volume-claim.yaml")
  vars = {
    name        = var.persistent_volume_claim_name
    namespace   = kubernetes_namespace.this.metadata.0.name
    volume_name = kubernetes_manifest.persistent_volume.manifest.metadata.name
  }
}

resource "kubernetes_manifest" "persistent_volume_claim" {
  manifest = yamldecode(data.template_file.persistent_volume_claim_manifest.rendered)
}
```

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${name}
  namespace: ${namespace}
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadOnlyMany
  storageClassName: hostpath
  volumeName: ${volume_name}

```

### Debug Output
```
> tf plan
╷
│ Error: Failed to determine GroupVersionResource for manifest
│ 
│   with kubernetes_manifest.persistent_volume_claim,
│   on main.tf line 28, in resource "kubernetes_manifest" "persistent_volume_claim":
│   28: resource "kubernetes_manifest" "persistent_volume_claim" {
│ 
│ unmarshaling unknown values is not supported
```

### Steps to Reproduce
1. `terraform plan`
