### ISSUE TITLE
Can't create a kyverno policy

### ISSUE THREAD

**Issue by alexppg** [hashicorp/terraform-provider-kubernetes#1427]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.14.11 
Kubernetes provider version: v2.5.0
Kubernetes version: v1.21.2-eks-0389ca3
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

```hcl
resource "kubernetes_manifest" "clusterpolicy_ingress" {
  provider = kubernetes-alpha
  manifest = {
    "apiVersion" = "kyverno.io/v1"
    "kind"       = "ClusterPolicy"
    "metadata" = {
      "name" = "ingress"
    }
    "spec" = {
      "background" = false
      "rules" = [
        {
          "match" = {
            "resources" = {
              "kinds" = [
                "Ingress",
              ]
            }
          }
          "name" = "Allow"
          "validate" = {
            "anyPattern" = [
              {
                "metadata" = {
                  "annotations" = {
                    "kubernetes.io/ingress.class" = "ingress-public"
                  }
                  "namespace" = "public"
                }
              },
              {
                "metadata" = {
                  "annotations" = {
                    "kubernetes.io/ingress.class" = "ingress-private"
                  }
                  "namespace" = "private"
                }
              },
              {
                "metadata" = {
                  "annotations" = {
                    "kubernetes.io/ingress.class" = "ingress-admin"
                  }
                  "namespace" = "kube-system|monitoring"
                }
              },
            ]
            "message" = "That combination of namespace/ingress.class is not allowed."
          }
        },
      ]
      "validationFailureAction" = "enforce"
    }
  }
}
terraform {
  required_providers {
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.5.0"
    }
  }
}
provider "kubernetes" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  experiments {
    manifest_resource = true
  }
}
provider "kubernetes-alpha" {
  host                   = data.aws_eks_cluster.cluster.endpoint
  cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
  token                  = data.aws_eks_cluster_auth.cluster.token
  version                = "0.4.1"
}
```

To install kyverno to be able to reproduce the isue you may use:

```hcl
resource "helm_release" "kyverno" {
  name       = "kyverno"
  namespace  = "kyverno"
  version    = "v1.4.0"
  repository = "https://kyverno.github.io/kyverno/"
  chart      = "kyverno"
  values     = [file("helm-values/kyverno.yml")]
}
provider "helm" {
  kubernetes {
    host                   = data.aws_eks_cluster.cluster.endpoint
    cluster_ca_certificate = base64decode(data.aws_eks_cluster.cluster.certificate_authority.0.data)
    token                  = data.aws_eks_cluster_auth.cluster.token
  }
}
```

The helm configuration:

```yaml
rbac:
  create: true
hostNetwork: true
dnsPolicy: "ClusterFirstWithHostNet"
config:
  # resource types to be skipped by kyverno policy engine
  # Make sure to surround each entry in quotes so that it doesn't get parsed
  # as a nested YAML list. These are joined together without spaces in the configmap
  resourceFilters:
  - "[Event,*,*]"
  - "[*,kube-public,*]"
  - "[*,kube-node-lease,*]"
  - "[Node,*,*]"
  - "[APIService,*,*]"
  - "[TokenReview,*,*]"
  - "[SubjectAccessReview,*,*]"
  - "[*,kyverno,*]"
  - "[Binding,*,*]"
  - "[ReplicaSet,*,*]"
  - "[ReportChangeRequest,*,*]"
  - "[ClusterReportChangeRequest,*,*]"

```

### Debug Output

https://pastebin-open.paradigmadigital.com/?091b2044f842b07a#VIU08YCPktdXUjr5w8UmKS2f6Qg8+XJAq8R0b5yfRF0=

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
What should have happened?
When using the main provider, with the experiments activated to be able to use the `kubernetes_manifest` resource, this code should be able to create the resource. 

### Actual Behavior
What actually happened?
It doesn't, and returns the `Provider produced inconsistent result after apply` error.

### Important Factoids

You may have noticed that I added the configuration of the kubernetes alpha provider. When using this provider with the `kubernetes_manifest`, it works as expected. 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

PD: Thanks for your awesome work!
