### ISSUE TITLE
Ability to add "csi" section when defining PV

### ISSUE THREAD

**Issue by tmetodie** [hashicorp/terraform-provider-kubernetes#1447]
### Description

When you deploy the EBS/EFS CSI driver you can add the CSI section in the specification of the PersistentVolume. However with Terraform you cannot specify this section and is really hard to manage the PV. Currently using null_resource.

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ${pv_name}
spec:
  capacity:
    storage: ${pv_size}Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ${sc_name}
  csi:                <<<<
    driver: efs.csi.aws.com
    volumeHandle: ${efs_id}
```
