### ISSUE TITLE
Failing `kubernetes_manifest` apply with kyverno policy

### ISSUE THREAD

**Issue by saschahemleb** [hashicorp/terraform-provider-kubernetes#1500]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.0.11
Kubernetes provider version: v2.6.1
Kubernetes version: v1.21.2
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "add_safe_to_evict" {
  manifest = yamldecode(file("add-safe-to-evict.yaml"))
}
```
```yaml
# add-safe-to-evict.yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-safe-to-evict
spec:
  rules:
    - name: annotate-empty-dir
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(cluster-autoscaler.kubernetes.io/safe-to-evict): "true"
          spec:
            volumes:
              - <(emptyDir): {}
```

### Debug Output

https://gist.github.com/saschahemleb/1398a2ca00ba33074a909ce301c0e809

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
What should have happened?
The apply operation should have finished successfuly

### Actual Behavior
What actually happened?
The resource is created in the k8s cluster, but the provider crashes with an error

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by saschahemleb** [comment]
I suspect that the provider has difficulties handling manifests with dynamic structures, like a list of maps with different attributes.\
The example policy in the OP is subject to the autogen feature of kyverno, where it will automatically generate the appropriate rules for other podcontroller resources (like daemonset and deployment). And so the api server returns the resource looking kinda like this:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-safe-to-evict
spec:
  background: true
  failurePolicy: Fail
  rules:
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        resources:
          kinds:
            - Pod
      mutate:
        patchStrategicMerge:
          metadata:
            annotations:
              +(cluster-autoscaler.kubernetes.io/safe-to-evict): 'true'
          spec:
            volumes:
              - <(emptyDir): {}
      name: annotate-empty-dir
      validate: {}
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        resources:
          kinds:
            - DaemonSet
            - Deployment
            - Job
            - StatefulSet
      mutate:
        patchStrategicMerge:
          spec:
            template:
              metadata:
                annotations:
                  +(cluster-autoscaler.kubernetes.io/safe-to-evict): 'true'
              spec:
                volumes:
                  - <(emptyDir): {}
      name: autogen-annotate-empty-dir
      validate: {}
    - exclude:
        resources: {}
      generate:
        clone: {}
      match:
        resources:
          kinds:
            - CronJob
      mutate:
        patchStrategicMerge:
          spec:
            jobTemplate:
              spec:
                template:
                  metadata:
                    annotations:
                      +(cluster-autoscaler.kubernetes.io/safe-to-evict): 'true'
                  spec:
                    volumes:
                      - <(emptyDir): {}
      name: autogen-cronjob-annotate-empty-dir
      validate: {}
  validationFailureAction: audit

```
And because the structure under `/spec/rules/-/mutate` is different between the list items, the provider fails with an error "lists must only contain one type of element".
