### ISSUE TITLE
Feature: GlobalNetworkPolicy (or custom YAML)

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-kubernetes#1556]
### Description

It would be nice to be able to supply custom resources such as:

```yaml
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-icmp-kube-02
spec:
  selector: "role == 'k8s-node'"
  order: 0
  ingress:
  - action: Allow
    protocol: ICMP
  egress:
  - action: Allow
    protocol: ICMP
```

Since https://github.com/hashicorp/terraform-provider-kubernetes-alpha  is archived we don't have an alternative.

### References

Copy of https://github.com/hashicorp/terraform-provider-kubernetes/issues/774
