### ISSUE TITLE
Failed to morph manifest to OAPI type

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-provider-kubernetes#1563]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.1.3
Kubernetes provider version: 2.7.1
Kubernetes version: v1.21.5-gke.1302
```

### Affected Resource(s)

- `kubernetes_manifest`

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "wildcard_tlscontext" {
  manifest = {
    apiVersion = "getambassador.io/v2"
    kind       = "TLSContext"
    metadata = {
      name      = var.wildcard_context
      namespace = var.chart_namespace
      labels = local.labels
    }

    spec = {
      ambassador_id = ["internal", "external"]

      hosts  = ["*"]
      secret = var.wildcard_host_secret

      min_tls_version = "v1.2"
      alpn_protocols  = join(",", ["h2", "http/1.1"])
    }
  }
}

```

### Panic Output

```
│ Error: Failed to morph manifest to OAPI type
│
│   with kubernetes_manifest.wildcard_tlscontext,
│   on main.tf line 98, in resource "kubernetes_manifest" "wildcard_tlscontext":
│   98: resource "kubernetes_manifest" "wildcard_tlscontext" {
│
│ AttributeName("spec"): [AttributeName("spec")] failed to morph object
│ element into object element:
│ AttributeName("spec").AttributeName("ambassador_id"):
│ [AttributeName("spec").AttributeName("ambassador_id")] failed to morph
│ object element into object element:
│ AttributeName("spec").AttributeName("ambassador_id"): type is nil
```

### Steps to Reproduce

Plan

### Expected Behavior
What should have happened?

Plan success.

### Actual Behavior
What actually happened?

Plan failed.

### Important Factoids

The original CRD definition can be found https://github.com/emissary-ingress/emissary/blob/v1.14.2/charts/ambassador/crds/getambassador.io_tlscontexts.yaml

After updating the CRD definition to https://github.com/emissary-ingress/emissary/blob/a3637a83ff04fd80a401d90300468815e3963eeb/cmd/entrypoint/crds.yaml#L2850 with the following changes:

Added a new API Version (`v3alpha1`)

Removed `ambassador_id` on `v2` because it used to be defined as 

```yaml
            ambassador_id:
              description: "AmbassadorID declares which Ambassador instances should pay attention to this resource.  May either be a string or a list of strings.  If no value is provided, the default is: \n    ambassador_id:    - \"default\""
              items:
                type: string
              oneOf:
              - type: string
              - type: array
```

because K8S 1.22 on do not support multiple types per field.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
