### ISSUE TITLE
kubernetes_manifest resources panics when a value depends on other resources

### ISSUE THREAD

**Issue by junaid-ali** [hashicorp/terraform-provider-kubernetes#1610]
I'm creating a configmap where one of the fields in the `data` section depends on another value. Running terraform apply causes a panic

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 0.14.11
Kubernetes provider version: 1.28
Kubernetes version: 1.20
```

### Affected Resource(s)

kubernetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "aws-auth" {
  manifest = {
    apiVersion = "v1"
    kind       = "ConfigMap"
    data       = {
      mapAccounts = yamlencode([])
      mapRoles    = yamldecode(module.eks.aws_auth_configmap_yaml)["data"].mapRoles <--- this value depends
      mapUsers    = yamlencode(local.map_users)
    }
    metadata = {
      name      = "aws-auth"
      namespace = "kube-system"
      labels = {
        "app.kubernetes.io/managed-by" = "Terraform"
      }
    }
  }

  depends_on = [module.eks.self_managed_node_groups]
}
```

### Panic Output

```
panic: ElementKeyString("mapRoles"): can't use tftypes.DynamicPseudoType as tftypes.String
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jrhouston** [comment]
Hi @junaid-ali I think you have reported this issue on the wrong project. Your example uses the `kubectl_manifest` resource which is part of the [kubectl provider](https://github.com/gavinbunney/terraform-provider-kubectl). The resource supported by this project is [kubernetes_manifest](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest).

**Comment by junaid-ali** [comment]
@jrhouston, thanks for pointing out the mistake. I was testing the `kubectl_manifest` as well from [kubectl provider](https://github.com/gavinbunney/terraform-provider-kubectl), and mistakenly pasted that manifest instead of the `kubernetes_manifest`. I have updated the description since the issue did appear in kubernetes provider's `kuberentes_manifest` resource.

**Comment by alexsomesan** [comment]
What type do you expect `yamldecode(module.eks.aws_auth_configmap_yaml)["data"].mapRoles` to be?

It looks like terraform is not able to determine the type of it, but the value expeected should be of type string. Depending on which type you're getting there, it needs to be converted to a string.

**Comment by junaid-ali** [comment]
`mapRoles` contains a list of AWS IAM role ARNs + other attributes, which we convert to string and pass to the configmap. When a new role is to be added to the list, that is yet to be created by terraform, the above error occurs.

P.S: `module.eks.aws_auth_configmap_yaml` is a yaml encoded value, and looks like below:
```yaml
data:
  mapRoles: |
    - rolearn: arn:aws:iam::111122223333:role/eksctl-my-cluster-nodegroup-standard-wo-NodeInstanceRole-1WP3NUE3O6UCF
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::111122223333:role/eksctl-my-cluster-nodegroup-standard-another-one
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: <A new role that's yet to be created by module.eks>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
```
