### ISSUE TITLE
horizontal_pod_autoscaler's scale_target_ref's api_version is not so optional

### ISSUE THREAD

**Issue by rafaelsierra** [hashicorp/terraform-provider-kubernetes#1622]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/google v4.12.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.8.0
Kubernetes version: 1.21.6-gke.1500
```

### Affected Resource(s)
- horizontal_pod_autoscaler

### Steps to Reproduce
1. Using GCP's GKE
1. Use terraform to create a pod deployment
1. Use terraform to create an `horizontal_pod_autoscaler` for such pod
1. Set the `horizontal_pod_autoscaler.spec.scale_target_ref`'s `kind` and `name` but do not set `api_version`
1. Apply the autoscaler resource
1. The pod won't be able to scale properly because it won't be able to read metrics (status is `Unable to read all metrics`)

### Expected Behavior
Since `api_version` is [optional](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/horizontal_pod_autoscaler#api_version), it is expected that hpa would work without having to set it

### Actual Behavior
HPA does not function because it can't read metrics

### Proposed solution
Update documentation to mention that leaving `api_version` empty may result in unexpected behavior

### Important Factoids
Running on GCP's GKE with the entire K8s cluster being managed by Terraform files

### References
https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/horizontal_pod_autoscaler#api_version

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @rafaelsierra,

Thank you for reporting this. The attribute `spec.scale_target_ref.api_version` is optional accoring to the releavant Kubernetes [structure](https://pkg.go.dev/k8s.io/api/autoscaling/v1#CrossVersionObjectReference).

I would like to share some research I have done.

- I wrote a basic manifest that has Deployment and HPA. Please pay attention that `spec.scaleTargetRef.apiVersion` is commented to reproduce the behavior that you are observing with the Kubernetes provider.
```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      labels:
        app: nginx2
    spec:
      containers:
      - name: nginx2
        image: nginx:1.21
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx2
spec:
  scaleTargetRef:
    #apiVersion: apps/v1
    kind: Deployment
    name: nginx2
  minReplicas: 5
  maxReplicas: 10

```

I could apply this manifest via `kubectl` and didn't get any error messages:
```
# kubectl apply -f deployment.yaml

deployment.apps/nginx2 created
horizontalpodautoscaler.autoscaling/nginx2 created
```

However, HPA couldn't find any matches:
```
# kubectl describe hpa nginx2
...
Events:
  Type     Reason          Age   From                       Message
  ----     ------          ----  ----                       -------
  Warning  FailedGetScale  7s    horizontal-pod-autoscaler  no matches for kind "Deployment" in group ""
```

I updated the original manifest by uncommented `spec.scaleTargetRef.apiVersion` and applied it via `kubectl` again:
```
# kubectl apply -f deployment.yaml

deployment.apps/nginx2 unchanged
horizontalpodautoscaler.autoscaling/nginx2 configured
```

Now HPA can find deployment and scale it accordingly:
```
# kubectl describe hpa nginx2
...
Events:
  Type     Reason                        Age                   From                       Message
  ----     ------                        ----                  ----                       -------
  Warning  FailedGetScale                37s (x10 over 2m52s)  horizontal-pod-autoscaler  no matches for kind "Deployment" in group ""
  Normal   SuccessfulRescale             22s                   horizontal-pod-autoscaler  New size: 5; reason: Current number of replicas below Spec.MinReplicas
```

- I wrote a basic manifest that has ReplicationController and HPA. Please pay attention that `spec.scaleTargetRef.apiVersion` is not presented here.
```yaml
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  scaleTargetRef:
    kind: ReplicationController
    name: nginx
  minReplicas: 5
  maxReplicas: 10
```

I could apply this manifest via `kubectl` and didn't get any error messages:
```
# kubectl apply -f rc.yaml

replicationcontroller/nginx created
horizontalpodautoscaler.autoscaling/nginx created
```

This time HPA could find matches and scale ReplicationController accordingly:
```
# kubectl describe hpa nginx
...
Events:
  Type    Reason             Age   From                       Message
  ----    ------             ----  ----                       -------
  Normal  SuccessfulRescale  12s   horizontal-pod-autoscaler  New size: 5; reason: Current number of replicas below Spec.MinReplicas
```

- The difference between these two examples is the API version that these resources(Deployment and ReplicationController) are part of.

```
# kubectl explain Deployment

KIND:     Deployment
VERSION:  apps/v1

# kubectl explain ReplicationController

KIND:     ReplicationController
VERSION:  v1
```

- HPA `spec.scaleTargetRef.apiVersion` remains optional for targets that are part of `core/v1` API, like `ReplicationController`. Kubernetes itself doesn't throw an error when you apply an HPA manifest for `apps/v1/Deployment` and doesn't specify target `apiVersion`. I would say, that the provider works as expected and by making attribute `api_version` required we can break some existing terraform code. However, I agree with you, that we need to update examples in our documentation and clarify the `api_version` attribute behavior.

Please let me know if that answers your question.

Thank you!
