### ISSUE TITLE
kubernetes_manifest fail with error Cannot create resource that already exists( count sequence)

### ISSUE THREAD

**Issue by sebglon** [hashicorp/terraform-provider-kubernetes#1713]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v2.11.0
Kubernetes provider version: v0.14.11
Kubernetes version: 1.22
```

### Affected Resource(s)

- kubernetes_manifest

### Terraform Configuration Files
Create yaml file called `external-metrics-reader.yaml`
```yaml
#only for test
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-metrics-reader
rules:
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - list
  - get
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-metrics-reader
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-metrics-reader
subjects:
- kind: ServiceAccount
  name: horizontal-pod-autoscaler
  namespace: kube-system
```
```hcl
locals {
  raw_custom_metrics_stackdriver_adapter_manifests = split("---", file("./external-metrics-reader.yaml"))
  hcl_custom_metrics_stackdriver_adapter_manifests = [for custom_metrics_stackdriver_adapter_manifest in local.raw_custom_metrics_stackdriver_adapter_manifests : yamldecode(custom_metrics_stackdriver_adapter_manifest)]
}

resource "kubernetes_manifest" "custom-metrics-stackdriver-adapter" {
  depends_on = [
    google_container_cluster.default
  ]

    count = length(local.hcl_custom_metrics_stackdriver_adapter_manifests)

  manifest = local.hcl_custom_metrics_stackdriver_adapter_manifests[count.index]

}

```

### Debug Output
```
Error: Cannot create resource that already exists

  on .terraform/modules/cluster-europe-west3-b/terraform/modules/cluster/cluster.tf line 137, in resource "kubernetes_manifest" "custom-metrics-stackdriver-adapter":
 137: resource "kubernetes_manifest" "custom-metrics-stackdriver-adapter" {

resource "/external-metrics-reader" already exists

```

### Steps to Reproduce

1. `kubectl get ClusterRole external-metrics-reader` return no resource found
2. `terraform apply` 
3. `kubectl get ClusterRole external-metrics-reader`
4. The creationTime is less than a 1s

### Expected Behavior
What should have happened?
Terraform not fail

### Actual Behavior
What actually happened?
terraform create the resource but fail on checking it.
It seems related to the order of creation.
If the resource 1 is created before the 2 it's OK
But if It create the resource 2 before, it fail

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
