### ISSUE TITLE
How to `wait_for` a specific named condition type?

### ISSUE THREAD

**Issue by kriswuollett** [hashicorp/terraform-provider-kubernetes#1750]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.2.3
Kubernetes Provider version: 2.11.0
Kubernetes version: 1.22
```

## Question

Given that simple status enums (state machine-like) are considered deprecated by the [Kubernetes SIG Architecture API conventions](https://github.com/kubernetes/community/blob/9a4dbd387823f2862ea2c5fa5209ef9b5863ff8e/contributors/devel/sig-architecture/api-conventions.md?plain=1#L442-L454), does [`wait_for`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/manifest#using-wait_for-to-block-create-and-update-calls) even support picking out a specific condition type to check its status field? The path expressions just seem to support plain map access, but not selecting based on the contents of the object value.

For example from the [Kubernetes Deployment docs](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/), how would you wait for `MinimumReplicasAvailable` status to become `True`?

```yaml
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2016-10-04T12:25:39Z
    lastUpdateTime: 2016-10-04T12:25:39Z
    message: Replica set "nginx-deployment-4262182780" is progressing.
    reason: ReplicaSetUpdated
    status: "True"
    type: Progressing
  - lastTransitionTime: 2016-10-04T12:25:42Z
    lastUpdateTime: 2016-10-04T12:25:42Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2016-10-04T12:25:39Z
    lastUpdateTime: 2016-10-04T12:25:39Z
    message: 'Error creating: pods "nginx-deployment-4262182780-" is forbidden: exceeded quota:
      object-counts, requested: pods=1, used: pods=3, limited: pods=2'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  observedGeneration: 3
  replicas: 2
  unavailableReplicas: 2
```

This seems like it would be a feature request?
