### ISSUE TITLE
daemonset node_selector is not used

### ISSUE THREAD

**Issue by MattGarner-N** [hashicorp/terraform-provider-kubernetes#1789]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.2.5
Kubernetes provider version: 2.11.0
Kubernetes version: 1.22.11
```

### Affected Resource(s)
- kubernetes_daemonset

### Terraform Configuration Files
```hcl
resource "kubernetes_daemonset" "example" {
  metadata {
    name      = "terraform-example"
    namespace = "something"
    labels = {
      test = "MyExampleApp"
    }
  }

  spec {
    selector {
      match_labels = {
        test = "MyExampleApp"
      }
    }

    template {
      metadata {
        labels = {
          test = "MyExampleApp"
        }
      }

      spec {
        node_selector = {
          kubernetes.io/os = "linux"
        }

        container {
          image = "nginx:1.21.6"
          name  = "example"

          resources {
            limits = {
              cpu    = "0.5"
              memory = "512Mi"
            }
            requests = {
              cpu    = "250m"
              memory = "50Mi"
            }
          }

          liveness_probe {
            http_get {
              path = "/"
              port = 80

              http_header {
                name  = "X-Custom-Header"
                value = "Awesome"
              }
            }

            initial_delay_seconds = 3
            period_seconds        = 3
          }

        }
      }
    }
  }
}
```

### Steps to Reproduce
1. `terraform plan` shows no node selector.
2. 'terraform apply' creates the daemonset without node selector spec.

### Expected Behavior
Node Selector should be have been added to the daemonset

### Actual Behavior
Node Selector is not added, not even in the Terraform plan.

### References

- [Documentation](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/daemonset#node_selector)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @MattGarner-N,

I have tried to reproduce this issue, but everything works as expected. Here is my Terraform code(I removed `spec.template.spec.container.resources` and `spec.template.spec.container.liveness_probe` for simplicity and added quotes around `kubernetes.io/os` since I got a syntax error from Terraform):

```hcl
terraform {
  required_providers {
    kubernetes = {
      source = "hashicorp/kubernetes"
      version = "2.11.0"
    }
  }
}

provider "kubernetes" {}

resource "kubernetes_daemonset" "example" {
  metadata {
    name      = "terraform-example"
    labels = {
      test = "MyExampleApp"
    }
  }

  spec {
    selector {
      match_labels = {
        test = "MyExampleApp"
      }
    }

    template {
      metadata {
        labels = {
          test = "MyExampleApp"
        }
      }

      spec {
        node_selector = {
          "kubernetes.io/os" = "linux"
        }

        container {
          image = "nginx:1.21.6"
          name  = "example"
        }
      }
    }
  }
}
```

Here is a part of the plan output I got:
```
Terraform will perform the following actions:

  # kubernetes_daemonset.example will be created
  + resource "kubernetes_daemonset" "example" {
 ...
              + spec {
                  + automount_service_account_token  = true
                  + dns_policy                       = "ClusterFirst"
                  + enable_service_links             = true
                  + host_ipc                         = false
                  + host_network                     = false
                  + host_pid                         = false
                  + hostname                         = (known after apply)
                  + node_name                        = (known after apply)
                  + node_selector                    = {
                      + "kubernetes.io/os" = "linux"
                    }
                  + restart_policy                   = "Always"
```

Here is the DaemonSet I got once applied this code:
```
k get daemonset terraform-example -o yaml                                                                                                                       ⎈ kind-
apiVersion: apps/v1
kind: DaemonSet
...
    spec:
      automountServiceAccountToken: true
      containers:
      - image: nginx:1.21.6
        imagePullPolicy: IfNotPresent
        name: example
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      enableServiceLinks: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always
      schedulerName: default-scheduler
```

Can you please share the Terraform plan that you get?

Thank you.
