### ISSUE TITLE
kubernetes_horizontal_pod_autoscaler_v2 adding behavior block automatically even if not defined in resource

### ISSUE THREAD

**Issue by patademahesh** [hashicorp/terraform-provider-kubernetes#1850]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.2.9
Kubernetes provider version: 2.13.1
Kubernetes version: 1.24.4
```

### Affected Resource(s)

- kubernetes_horizontal_pod_autoscaler_v2

### Terraform Configuration Files
```hcl
resource "kubernetes_horizontal_pod_autoscaler_v2" "xxx" {
  metadata {
    name = "xxx-web-hpa"
    namespace = var.service
  }

  spec {
    min_replicas = 1
    max_replicas = 25

    scale_target_ref {
      api_version = "apps/v1"
      kind = "Deployment"
      name = kubernetes_deployment_v1.xxx.metadata[0].name
    }

    metric {
      type = "Resource"
      resource {
        name = "cpu"
        target {
          type = "Utilization"
          average_utilization = 60
        }
      }
    }
  }
}
```

### Debug Output
$ terraform apply
```
  ~ update in-place

Terraform will perform the following actions:

  # kubernetes_horizontal_pod_autoscaler_v2.xxx will be updated in-place
  ~ resource "kubernetes_horizontal_pod_autoscaler_v2" "xxx" {
        id = "xxx-ag/xxx-web-hpa"

      ~ spec {
            # (3 unchanged attributes hidden)

          ~ behavior {
              - scale_down {
                  - select_policy                = "Max" -> null
                  - stabilization_window_seconds = 0 -> null

                  - policy {
                      - period_seconds = 15 -> null
                      - type           = "Percent" -> null
                      - value          = 100 -> null
                    }
                }

              - scale_up {
                  - select_policy                = "Max" -> null
                  - stabilization_window_seconds = 0 -> null

                  - policy {
                      - period_seconds = 15 -> null
                      - type           = "Pods" -> null
                      - value          = 4 -> null
                    }
                  - policy {
                      - period_seconds = 15 -> null
                      - type           = "Percent" -> null
                      - value          = 100 -> null
                    }
                }
            }

            # (2 unchanged blocks hidden)
        }

        # (1 unchanged block hidden)
    }
```
Kubernetes HPA spec output:
```
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 25
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xxxx
```

### Steps to Reproduce

1. `terraform apply`

### Expected Behavior
What should have happened?
It should have added only **metrics** block in Kubernetes spec.

### Actual Behavior
What actually happened?
It's adding extra **behavior** block in Kubernetes spec and on every terraform apply it shows an update in-place to remove the behavior block.
