### ISSUE TITLE
kubernetes_network_policy selector based on other namespace and pod_selector

### ISSUE THREAD

**Issue by uwebartels** [hashicorp/terraform-provider-kubernetes#1868]
Hi,

according to the documentation I don't see how to create a networkpolicy like shown below.
this is a functioning networkpolicy.
I see how to create a namespace_selector with labels, but together with a pod-selector and labels...

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  namespace: test
  name: ap
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: ap
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            role: infra
        podSelector:
          matchLabels:
            app.kubernetes.io/name: ingress-nginx
      ports:
        - protocol: TCP
          port: 5556
YAML
}
```

## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.1.6
Kubernetes Provider version: 4.30.0
Kubernetes version: 1.20.15
```
