### ISSUE TITLE
Suppor `--as` from kubectl in kubernetes provider to support impersonation

### ISSUE THREAD

**Issue by anhdle14** [hashicorp/terraform-provider-kubernetes#1907]
### Description

Support this args from `man kubectl` so we can dynamically impersonate via provider. 

```
OPTIONS
       --as=""   Username to impersonate for the operation. User could be a
       regular user or a service account in a namespace.

       --as-group=[]  Group to impersonate for the operation, this flag can be
       repeated to specify multiple groups.

       --as-uid=""    UID to impersonate for the operation.
```

### Potential Terraform Configuration

```hcl
provider "kubernetes" {
  as="a-user"
  as_group="a-group"
  as_uid="a-uid"
  ...
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by arybolovlev** [comment]
Hi @anhdle14,

Can you please share use cases for these options for the provider?

Thanks.

**Comment by anhdle14** [comment]
Hi @arybolovlev, currently we are maintaining our own Kubernetes cluster with permission and role to bind between a namespace and group. We also used OIDC via [`pinniped`](https://pinniped.dev/) to allow user to promote themselves between `readonly` role to `editor` role when needed. 

The KUBECONFIG looks something like this:

```yaml
# ....
- name: ${REGION}-pinniped
  user:
    # NOTE: normally the user login as readonly. And we only allow them to edit with arg `--as $NAMESPACE-admin`
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - oidc
      - --enable-concierge
      - --concierge-api-group-suffix=pinniped.dev
      - --concierge-authenticator-name=supervisor
      - --concierge-authenticator-type=jwt
      - --concierge-endpoint=https://concierge.example.com
      - --concierge-ca-bundle-data=<REDACTED>
      - --issuer=https://issuer.example.com
      - --client-id=pinniped-cli
      - --scopes=offline_access,openid,pinniped:request-audience
      - --request-audience=example.com
      - --upstream-identity-provider-name=azure-ad
      - --upstream-identity-provider-type=oidc
      - --upstream-identity-provider-flow=browser_authcode
      command: pinniped
      env: []
      installHint: The pinniped CLI does not appear to be installed.  See https://get.pinniped.dev/cli
        for more details
      interactiveMode: IfAvailable
      provideClusterInfo: true
```

It is fine if we patch the Kubeconfig with `yq e '.users[].user.as = "${NAMESPACE}-admin"' kube_config_file`. But Terraform K8s provider should be able to patch it as well. Just like [`--user`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#config_context_auth_info) in current provider.
