### ISSUE TITLE
Best/Simpler way to apply configmap for AWS EKS

### ISSUE THREAD

**Issue by jauyzed** [hashicorp/terraform-provider-kubernetes#1938]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.0
Kubernetes Provider version: 2.10
Kubernetes version: 1.21
```
## Terraform configuration
```hcl
Enter your configuration here.
```

## Question

What is the simplest way to apply config maps to a cluster via  kubernetes provider. The examples in the documentation do not provide much information. 

I have a following aws-auth-configmap yaml to any EKS cluster which is self managed worker nodes

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::some-acct-number:role/some-role-name
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

```
and proxy env variable config map for a proxy enviroments
```
apiVersion: v1
kind: ConfigMap
metadata:
   name: proxy-environment-variables
   namespace: kube-system
data:
   HTTP_PROXY: http://proxy.fb:8080
   HTTPS_PROXY: http://proxy.fb:8080
   NO_PROXY: eks.amazonaws.com,s3.amazonaws.com,.s3.us-west-2.amazonaws.com,ec2.us-west-2.amazonaws.com
```
