### ISSUE TITLE
Secret not getting attached to Service account

### ISSUE THREAD

**Issue by varunvijayagopal** [hashicorp/terraform-provider-kubernetes#2029]
Am trying to upgrade to 1.24, and in 1.24 I found that it doesn't automatically create a secret for service account 

Am trying below 
```
resource "kubernetes_secret_v1" "jenkins_deploy_clusterrole_secret" {
  metadata {
    name        = "${var.jenkins_deploy_sa}-token"
    namespace = var.aks_rbac_namespace
    annotations = {
      "kubernetes.io/service-account.name" = var.jenkins_deploy_sa
    }
  }
  type = "kubernetes.io/service-account-token"
  depends_on = [data.kubernetes_service_account.jenkins_deploy_clusterrole_sa]
}
```

this creates secret as expected and I can see correct Service account name and uid when I describe the secret                                                                                                                                                                           
```
 metadata:                                                                                                                                                                                                                                                
     annotations:              
        kubernetes.io/service-account.name: jenkins-admin   
        kubernetes.io/service-account.uid: 9b24a484-57c6-4454-bb99-c77b2ebfdd87  
```

however when I see service account I still don't see any secrets attached which used to come when it creates automatically.
Do we need to attach secret manually by editing service account ?

Am using  2.18.1 version of kubernetes provider
