### ISSUE TITLE
Terraform can't modify GKE cluster because "User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace"

### ISSUE THREAD

**Issue by SehiiRohoza** [hashicorp/terraform-provider-kubernetes#2102]
Hi there,

Recently I found an issue with a code that worked fine before (at least on the 5th of May) without any issues.

### Terraform Version, Provider Version and Kubernetes Version
```
Terraform version: v1.4.6
Kubernetes provider version: v2.20.0
Kubernetes version: 1.24.10-gke.2300
```

### Affected Resource(s)
namespaces (at least)

### Terraform Configuration Files
main.tf
```
provider "google" {
  project = local.project_id
}

provider "google-beta" {
  project = local.project_id
}

data "google_client_config" "default" {}

data "google_container_cluster" "gke_cluster" {
  name     = "${var.environment}-cluster"
  location = local.gke_cluster_location
  project  = local.project_id
}

provider "kubernetes" {
  host                   = "https://${data.google_container_cluster.gke_cluster.endpoint}"
  token                  = data.google_client_config.default.access_token
  cluster_ca_certificate = base64decode(data.google_container_cluster.gke_cluster.master_auth[0].cluster_ca_certificate)
}

provider "helm" {
  kubernetes {
    host                   = "https://${data.google_container_cluster.gke_cluster.endpoint}"
    token                  = data.google_client_config.default.access_token
    cluster_ca_certificate = base64decode(data.google_container_cluster.gke_cluster.master_auth[0].cluster_ca_certificate)
  }
}
```
k8s_namespaces.tf
```
resource "kubernetes_namespace" "otel" {
  metadata {
    name = var.k8s_otel_namespace_name
  }
}

resource "kubernetes_namespace" "proxysql" {
  metadata {
    name = "proxysql"
  }
}
```

### Output
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: namespaces "otel" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "otel"
│
│   with kubernetes_namespace.otel,
│   on k8s_namespaces.tf line 1, in resource "kubernetes_namespace" "otel":
│    1: resource "kubernetes_namespace" "otel" {
│
╵
╷
│ Error: namespaces "proxysql" is forbidden: User "system:anonymous" cannot get resource "namespaces" in API group "" in the namespace "proxysql"
│
│   with kubernetes_namespace.proxysql,
│   on k8s_namespaces.tf line 7, in resource "kubernetes_namespace" "proxysql":
│    7: resource "kubernetes_namespace" "proxysql" {
│
```

### Steps to Reproduce
1. Create GKE cluster 
2. Try to deploy resources into the GKE cluster

### Expected Behavior
Resources should be create in the GKE cluster

### Actual Behavior
Error while running `terraform plan`

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by TejaBeta** [comment]
Temporary fix

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: reader
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: reader
subjects:
- kind: User
  name: system:anonymous
roleRef:
  kind: ClusterRole
  name: reader
  apiGroup: rbac.authorization.k8s.io
```
