### ISSUE TITLE
Imported CRDs show many changes in plan

### ISSUE THREAD

**Issue by artuzielinskirem2** [hashicorp/terraform-provider-kubernetes#2109]
I'm trying to manage updating CRDs from terraform. I'd like to import current CRDs from k8s and upgrade them using terraform. 

But when terraform compare CRDs from state with CRDs from yaml file (initial source of CRD from cluster) it show many changes to apply. There not changes should appear. 

### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.3.2
Kubernetes provider version: v2.20.0
Kubernetes version: 1.22.17
```

### Steps to Reproduce
1. Apply CRDs on k8s from authorizationpolicies.yaml  (via kubectl)
2. Import this CRD into terraform state 
```
terraform import '(...).module.istio_crds.kubernetes_manifest.istio_crds["crds/authorizationpolicies.yaml"]' "apiVersion=apiextensions.k8s.io/v1,kind=CustomResourceDefinition,name=authorizationpolicies.security.istio.io"
```
3. Run terraform plan using the same yaml file to see differences

### Expected Behavior
No changes would appear in plan

### Actual Behavior
Many changes appear in terraform plan

### Affected Resource(s)
CustomResourceDefinition 

authorizationpolicies.yaml
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: istio-pilot
    chart: istio
    heritage: Tiller
    istio: security
    release: istio
  name: authorizationpolicies.security.istio.io
spec:
  group: security.istio.io
  names:
    categories:
    - istio-io
    - security-istio-io
    kind: AuthorizationPolicy
    listKind: AuthorizationPolicyList
    plural: authorizationpolicies
    singular: authorizationpolicy
  scope: Namespaced
  versions:
  - name: v1beta1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            description: 'Configuration for access control on workloads. See more
              details at: https://istio.io/docs/reference/config/security/authorization-policy.html'
            oneOf:
            - not:
                anyOf:
                - required:
                  - provider
            - required:
              - provider
            properties:
              action:
                description: Optional.
                enum:
                - ALLOW
                - DENY
                - AUDIT
                - CUSTOM
                type: string
              provider:
                description: Specifies detailed configuration of the CUSTOM action.
                properties:
                  name:
                    description: Specifies the name of the extension provider.
                    type: string
                type: object
              rules:
                description: Optional.
                items:
                  properties:
                    from:
                      description: Optional.
                      items:
                        properties:
                          source:
                            description: Source specifies the source of a request.
                            properties:
                              ipBlocks:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              namespaces:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notIpBlocks:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notNamespaces:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notPrincipals:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notRemoteIpBlocks:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notRequestPrincipals:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              principals:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              remoteIpBlocks:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              requestPrincipals:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                            type: object
                        type: object
                      type: array
                    to:
                      description: Optional.
                      items:
                        properties:
                          operation:
                            description: Operation specifies the operation of a request.
                            properties:
                              hosts:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              methods:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notHosts:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notMethods:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notPaths:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              notPorts:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              paths:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                              ports:
                                description: Optional.
                                items:
                                  type: string
                                type: array
                            type: object
                        type: object
                      type: array
                    when:
                      description: Optional.
                      items:
                        properties:
                          key:
                            description: The name of an Istio attribute.
                            type: string
                          notValues:
                            description: Optional.
                            items:
                              type: string
                            type: array
                          values:
                            description: Optional.
                            items:
                              type: string
                            type: array
                        type: object
                      type: array
                  type: object
                type: array
              selector:
                description: Optional.
                properties:
                  matchLabels:
                    additionalProperties:
                      type: string
                    type: object
                type: object
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
    subresources:
      status: {}
```

### Terraform Configuration Files
```
resource "kubernetes_manifest" "istio_crds" {
  for_each = fileset(path.module, "crds/authorizationpolicies.yaml")
  manifest = yamldecode(file("${path.module}/${each.value}"))
}

```

### Plan output
```
(...).module.istio_crds.kubernetes_manifest.istio_crds["crds/authorizationpolicies.yaml"]: Refreshing state...

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # (...).module.istio_crds.kubernetes_manifest.istio_crds["crds/authorizationpolicies.yaml"] will be updated in-place
  ~ resource "kubernetes_manifest" "istio_crds" {
      + manifest = {
          + apiVersion = "apiextensions.k8s.io/v1"
          + kind       = "CustomResourceDefinition"
          + metadata   = {
              + annotations = {
                  + "helm.sh/resource-policy" = "keep"
                }
              + labels      = {
                  + app      = "istio-pilot"
                  + chart    = "istio"
                  + heritage = "Tiller"
                  + istio    = "security"
                  + release  = "istio"
                }
              + name        = "authorizationpolicies.security.istio.io"
            }
          + spec       = {
              + group    = "security.istio.io"
              + names    = {
                  + categories = [
                      + "istio-io",
                      + "security-istio-io",
                    ]
                  + kind       = "AuthorizationPolicy"
                  + listKind   = "AuthorizationPolicyList"
                  + plural     = "authorizationpolicies"
                  + singular   = "authorizationpolicy"
                }
              + scope    = "Namespaced"
              + versions = [
                  + {
                      + name         = "v1beta1"
                      + schema       = {
                          + openAPIV3Schema = {
                              + properties = {
                                  + spec   = {
                                      + description = "Configuration for access control on workloads. See more details at: https://istio.io/docs/reference/config/security/authorization-policy.html"
                                      + oneOf       = [
                                          + {
                                              + not = {
                                                  + anyOf = [
                                                      + {
                                                          + required = [
                                                              + "provider",
                                                            ]
                                                        },
                                                    ]
                                                }
                                            },
                                          + {
                                              + required = [
                                                  + "provider",
                                                ]
                                            },
                                        ]
                                      + properties  = {
                                          + action   = {
                                              + description = "Optional."
                                              + enum        = [
                                                  + "ALLOW",
                                                  + "DENY",
                                                  + "AUDIT",
                                                  + "CUSTOM",
                                                ]
                                              + type        = "string"
                                            }
                                          + provider = {
                                              + description = "Specifies detailed configuration of the CUSTOM action."
                                              + properties  = {
                                                  + name = {
                                                      + description = "Specifies the name of the extension provider."
                                                      + type        = "string"
                                                    }
                                                }
                                              + type        = "object"
                                            }
                                          + rules    = {
                                              + description = "Optional."
                                              + items       = {
                                                  + properties = {
                                                      + from = {
                                                          + description = "Optional."
                                                          + items       = {
                                                              + properties = {
                                                                  + source = {
                                                                      + description = "Source specifies the source of a request."
                                                                      + properties  = {
                                                                          + ipBlocks             = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + namespaces           = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notIpBlocks          = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notNamespaces        = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notPrincipals        = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notRemoteIpBlocks    = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notRequestPrincipals = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + principals           = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + remoteIpBlocks       = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + requestPrincipals    = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                        }
                                                                      + type        = "object"
                                                                    }
                                                                }
                                                              + type       = "object"
                                                            }
                                                          + type        = "array"
                                                        }
                                                      + to   = {
                                                          + description = "Optional."
                                                          + items       = {
                                                              + properties = {
                                                                  + operation = {
                                                                      + description = "Operation specifies the operation of a request."
                                                                      + properties  = {
                                                                          + hosts      = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + methods    = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notHosts   = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notMethods = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notPaths   = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + notPorts   = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + paths      = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                          + ports      = {
                                                                              + description = "Optional."
                                                                              + items       = {
                                                                                  + type = "string"
                                                                                }
                                                                              + type        = "array"
                                                                            }
                                                                        }
                                                                      + type        = "object"
                                                                    }
                                                                }
                                                              + type       = "object"
                                                            }
                                                          + type        = "array"
                                                        }
                                                      + when = {
                                                          + description = "Optional."
                                                          + items       = {
                                                              + properties = {
                                                                  + key       = {
                                                                      + description = "The name of an Istio attribute."
                                                                      + type        = "string"
                                                                    }
                                                                  + notValues = {
                                                                      + description = "Optional."
                                                                      + items       = {
                                                                          + type = "string"
                                                                        }
                                                                      + type        = "array"
                                                                    }
                                                                  + values    = {
                                                                      + description = "Optional."
                                                                      + items       = {
                                                                          + type = "string"
                                                                        }
                                                                      + type        = "array"
                                                                    }
                                                                }
                                                              + type       = "object"
                                                            }
                                                          + type        = "array"
                                                        }
                                                    }
                                                  + type       = "object"
                                                }
                                              + type        = "array"
                                            }
                                          + selector = {
                                              + description = "Optional."
                                              + properties  = {
                                                  + matchLabels = {
                                                      + additionalProperties = {
                                                          + type = "string"
                                                        }
                                                      + type                 = "object"
                                                    }
                                                }
                                              + type        = "object"
                                            }
                                        }
                                      + type        = "object"
                                    }
                                  + status = {
                                      + type                                 = "object"
                                      + x-kubernetes-preserve-unknown-fields = true
                                    }
                                }
                              + type       = "object"
                            }
                        }
                      + served       = true
                      + storage      = true
                      + subresources = {
                          + status = {}
                        }
                    },
                ]
            }
        }
      ~ object   = {
          ~ metadata   = {
              ~ annotations                = {
                  - "helm.sh/resource-policy" = "keep"
                } -> (known after apply)
              ~ labels                     = {
                  - "app"      = "istio-pilot"
                  - "chart"    = "istio"
                  - "heritage" = "Tiller"
                  - "istio"    = "security"
                  - "release"  = "istio"
                } -> (known after apply)
                name                       = "authorizationpolicies.security.istio.io"
                # (13 unchanged elements hidden)
            }
            # (3 unchanged elements hidden)
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Important Factoids
EKS managed kubernetes
