### ISSUE TITLE
kubernetes_manifest can't apply valid yml

### ISSUE THREAD

**Issue by davidgiga1993** [hashicorp/terraform-provider-kubernetes#2123]
### Terraform Version, Provider Version and Kubernetes Version

```
terraform -v
Terraform v1.4.6
on windows_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v5.0.1
+ provider registry.terraform.io/hashicorp/helm v2.9.0
+ provider registry.terraform.io/hashicorp/kubernetes v2.20.0
```

### Affected Resource(s)
- kubernetes_manifest

### Terraform Configuration Files
```yml
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: companyrdscomposition
  labels:
    # An optional convention is to include a label of the XRD. This allows
    # easy discovery of compatible Compositions.
    crossplane.io/xrd: xdbinstances.company.com
    # The following label marks this Composition for GCP. This label can
    # be used in 'compositionSelector' in an XR or Claim.
    provider: provider-aws
spec:

  # Each Composition must declare that it is compatible with a particular type
  # of Composite Resource using its 'compositeTypeRef' field. The referenced
  # version must be marked 'referenceable' in the XRD that defines the XR.
  compositeTypeRef:
    apiVersion: dbinstances.company.com/v1alpha1
    kind: XDbInstance

  # Each Composition must specify at least one composed resource template. In
  # this case the Composition tells Crossplane that it should create, update, or
  # delete a CloudSQLInstance whenever someone creates, updates, or deletes an
  # XPostgresSQLInstance.
  resources:

    # It's good practice to provide a unique name for each entry. Note that
    # this identifies the resources entry within the Composition - it's not
    # the name the CloudSQLInstance. The 'name' field will be required in a
    # future version of this API.
    - name: rdsSubnetGroup

      # The 'base' template for the CloudSQLInstance Crossplane will create.
      # You can use the base template to specify fields that never change, or
      # default values for fields that may optionally be patched over. Bases must
      # be a valid Crossplane resource - a Managed Resource, Composite Resource,
      # or a ProviderConfig.
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: DBSubnetGroup
        metadata:
          name: workload-subnet
        spec:
          forProvider:
            region: eu-central-1
            description: "Subnet for crossplane RDS instances"
            subnetIds:
              # AZ a and b
              - subnet-03acd8cfcba74c16c
              - subnet-0827394c90552c6e0
          providerRef:
            name: provider-aws

      # Each resource can optionally specify a set of 'patches' that copy fields
      # from (or to) the XR.
      patches:
        - type: PatchSet
          patchSetName: metadata
    - name: rds
      base:
        apiVersion: database.aws.crossplane.io/v1beta1
        kind: RDSInstance
        metadata:
          name: rds-example
          namespace: david-test
        spec:
          providerRef:
            name: provider-aws
          forProvider:
            region: eu-central-1
            dbInstanceClass: db.t3.micro
            masterUsername: mainuser
            engine: mysql
            engineVersion: "8.0.32"
            skipFinalSnapshotBeforeDeletion: true
            # Reuse portal for testing
            dbName: RdsExample

            multiAZ: false
            dbSubnetGroupName: "workload-subnet"
            backupRetentionPeriod: 2

            storageType: gp3
            allocatedStorage: 20
            maxAllocatedStorage: 25
            storageEncrypted: true
            kmsKeyId: "alias/aws/rds"

      patches:
        - type: PatchSet
          patchSetName: metadata

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.allocatedStorage
          transforms:
            - type: math
              math:
                type: ClampMin
                clampMin: 20

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.storageGB
          toFieldPath: spec.forProvider.maxAllocatedStorage
          transforms:
            - type: math
              math:
                type: ClampMin
                clampMin: 20
            - type: math
              math:
                type: Multiply
                multiply: 2

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.dbName
          toFieldPath: spec.forProvider.dbName

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.dbInstanceClass
          toFieldPath: spec.forProvider.dbInstanceClass

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.engine
          toFieldPath: spec.forProvider.engine

        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.engineVersion
          toFieldPath: spec.forProvider.engineVersion

      connectionDetails:
        - name: endpoint
          fromConnectionSecretKey: endpoint
        - name: password
          fromConnectionSecretKey: password
        - name: port
          fromConnectionSecretKey: port
        - name: username
          fromConnectionSecretKey: username

  # If you find yourself repeating patches a lot you can group them as a named
  # 'patch set' then use a PatchSet type patch to reference them.
  patchSets:
    - name: metadata
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: metadata.namespace
          toFieldPath: spec.forProvider.tags[InvoiceToProductName]
```

```hcl
resource "kubernetes_manifest" "db-composition" {
  manifest = yamldecode(file("${path.module}/db-composition.yml"))
}
```

### Debug Output
Due to confidentiality of the project I can't provide the full debug output

### Steps to Reproduce
1. `terraform apply`

### Expected Behavior
Terraform should be able to import any valid k8s yml files

### Actual Behavior
Terraform type error:
```
│ Error: Failed to set computed attributes in new resource state
│
│   with module.crossplane-xrd.kubernetes_manifest.db-composition,
│   on crossplane-xrd\xrd.tf line 5, in resource "kubernetes_manifest" "db-composition":
│    5: resource "kubernetes_manifest" "db-composition" {
│
│ AttributeName("transforms"): can't use tftypes.Tuple[tftypes.Object["convert":tftypes.Object["format":tftypes.String, "toType":tftypes.String], "map":tftypes.Map[tftypes.DynamicPseudoType],
│ "match":tftypes.Object["fallbackTo":tftypes.String, "fallbackValue":tftypes.DynamicPseudoType, "patterns":tftypes.Tuple[tftypes.Object["literal":tftypes.String, "regexp":tftypes.String, "result":tftypes.DynamicPseudoType,     
│ "type":tftypes.String]]], "math":tftypes.Object["clampMax":tftypes.Number, "clampMin":tftypes.Number, "multiply":tftypes.Number, "type":tftypes.String], "string":tftypes.Object["convert":tftypes.String, "fmt":tftypes.String,  
│ "regexp":tftypes.Object["group":tftypes.Number, "match":tftypes.String], "trim":tftypes.String, "type":tftypes.String], "type":tftypes.String]] as tftypes.Tuple[tftypes.Object["convert":tftypes.Object["format":tftypes.String, 
│ "toType":tftypes.String], "map":tftypes.Map[tftypes.DynamicPseudoType], "match":tftypes.Object["fallbackTo":tftypes.String, "fallbackValue":tftypes.DynamicPseudoType,
│ "patterns":tftypes.Tuple[tftypes.Object["literal":tftypes.String, "regexp":tftypes.String, "result":tftypes.DynamicPseudoType, "type":tftypes.String]]], "math":tftypes.Object["clampMax":tftypes.Number,
│ "clampMin":tftypes.Number, "multiply":tftypes.Number, "type":tftypes.String], "string":tftypes.Object["convert":tftypes.String, "fmt":tftypes.String, "regexp":tftypes.Object["group":tftypes.Number, "match":tftypes.String],    
│ "trim":tftypes.String, "type":tftypes.String], "type":tftypes.String], tftypes.Object["convert":tftypes.Object["format":tftypes.String, "toType":tftypes.String], "map":tftypes.Map[tftypes.DynamicPseudoType],
│ "match":tftypes.Object["fallbackTo":tftypes.String, "fallbackValue":tftypes.DynamicPseudoType, "patterns":tftypes.Tuple[tftypes.Object["literal":tftypes.String, "regexp":tftypes.String, "result":tftypes.DynamicPseudoType,     
│ "type":tftypes.String]]], "math":tftypes.Object["clampMax":tftypes.Number, "clampMin":tftypes.Number, "multiply":tftypes.Number, "type":tftypes.String], "string":tftypes.Object["convert":tftypes.String, "fmt":tftypes.String,  
│ "regexp":tftypes.Object["group":tftypes.Number, "match":tftypes.String], "trim":tftypes.String, "type":tftypes.String], "type":tftypes.String]]

```

### Important Factoids
- Classic kubernetes provider setup. I can import the yml using kubectl without any issues.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
