### ISSUE TITLE
kubernetes_manifest secret stringData inconsistent error

### ISSUE THREAD

**Issue by akumar-99** [hashicorp/terraform-provider-kubernetes#2184]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v1.5.1
Kubernetes provider version: 2.21.1
Kubernetes version: 1.24
```

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "eck-secret-elastic-filebeat-ingestion-role" {
  manifest = yamldecode(templatefile("../scripts/eck/eck-secret-elastic-filebeat-ingestion-role.yaml", {
    namespace = kubernetes_namespace.observability.metadata[0].name
  }))
}
```

```yaml
kind: Secret
apiVersion: v1
metadata:
  name: elastic-filebeat-ingestion-role
  namespace: ${namespace}
stringData:
  roles.yml: |-
    elastic-filebeat-ingestion-role:
      run_as: []
      cluster: [
        "monitor",
        "all",
        "manage"
      ]
      indices:
      - names: [ "*-pod-*" ]
        privileges: [
          "create",
          "create_doc",
          "delete",
          "index",
          "write",
          "all",
          "auto_configure",
          "create_index",
          "manage"
        ]
        field_security:
          grant: [ "*" ]

```

### Debug Output

https://gist.github.com/akumar-99/99a271e72ddf59b43ca146bd2d57d988
### Steps to Reproduce

`terraform apply -target=kubernetes_manifest.eck-secret-elastic-filebeat-ingestion-role`
### Expected Behavior
The kubernetes secret should have been created without any error.
### Actual Behavior
The resource got created successfully but terraform gave an error.
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to kubernetes_manifest.eck-secret-elastic-filebeat-ingestion-role, provider
│ "provider[\"registry.terraform.io/hashicorp/kubernetes\"]" produced an unexpected new value: .object.stringData: was
│ cty.MapVal(map[string]cty.Value{"roles.yml":cty.StringVal("elastic-filebeat-ingestion-role:\n  run_as: []\n  cluster: [\n    \"monitor\",\n
│ \"all\",\n    \"manage\"\n  ]\n  indices:\n  - names: [ \"*-pod-*\" ]\n    privileges: [\n      \"create\",\n      \"create_doc\",\n
│ \"delete\",\n      \"index\",\n      \"write\",\n      \"all\",\n      \"auto_configure\",\n      \"create_index\",\n      \"manage\"\n    ]\n
│ field_security:\n      grant: [ \"*\" ]")}), but now null.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
