### ISSUE TITLE
Ignore CRD check flag in the kubernetes_manifest resource

### ISSUE THREAD

**Issue by akumar-99** [hashicorp/terraform-provider-kubernetes#2187]
### Description
Currently, in the planning phase, it is checked if the CRD exists and if not, the code fails with an error. There should be a way to add a flag to disable the CRD check and then with a combination of depends_on and wait_for_k8s_resource, we can apply the following configuration in a single `terraform apply`. Currently, I need to run it at least twice and manage them seperately.

### Potential Terraform Configuration
```hcl
resource "helm_release" "eck-operator" {
  name       = "eck-operator"
  repository = "https://helm.elastic.co"
  chart      = "eck-operator"
  version    = "2.8.0"
  namespace  = kubernetes_namespace.observability.metadata[0].name
  values = [
    "${file("../scripts/values-eck-operator.yml")}"
  ]
}

resource "kubernetes_manifest" "eck-elasticsearch" {
  depends_on = [helm_release.eck-operator]
  manifest = yamldecode(templatefile("../scripts/eck/eck-elasticsearch.yaml", {
    namespace = kubernetes_namespace.observability.metadata[0].name
  }))
  wait_for_k8s_resource {
    apiVersion = "elasticsearch.k8s.elastic.co/v1"
    kind = "Elasticsearch"
  }
}
```

```yaml
# ../scripts/eck/eck-elasticsearch.yaml

apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: ${namespace}
spec:
  version: 8.8.2
  auth:
    fileRealm:
      - secretName: elastic-filebeat-ingestion-user
    roles:
      - secretName: elastic-filebeat-ingestion-role
  nodeSets:
    - name: master
      count: 1
      config:
        node:
          roles:
            - master
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp3
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 100m
                  memory: 2000Mi
                limits:
                  cpu: 500m
                  memory: 2500Mi
    - name: data
      count: 1
      config:
        node:
          roles:
            - data
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp3
      podTemplate:
        spec:
          nodeSelector:
            workload-type: observability
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 100m
                  memory: 2Gi
                limits:
                  cpu: 500m
                  memory: 2Gi

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
