### ISSUE TITLE
An option ignore deletion of a resource

### ISSUE THREAD

**Issue by akumar-99** [hashicorp/terraform-provider-kubernetes#2188]
### Description
In here, the secret I create using `kubernetes_manifest.eck-elastic-superuser` is finally controlled by `kubernetes_manifest.eck-elasticsearch` CRD in Kuberenetes. So when we run terraform destroy, it would first delete `kubernetes_manifest.eck-elasticsearch` which would delete the secret on Kubernetes cluster and when terraform will try to destroy  `kubernetes_manifest.eck-elastic-superuser`, it will get an error. 

So we can add a `apply_only` flag, that would only add the resource and will ignore it on deletion.

### Potential Terraform Configuration

```hcl
resource "kubernetes_manifest" "eck-elastic-superuser" {
  manifest = yamldecode(templatefile("../scripts/eck/eck-elastic-superuser.yaml", {
    namespace = kubernetes_namespace.observability.metadata[0].name,
    password  = data.vault_generic_secret.eck.data["elastic"]
  }))

  apply_only = true
}

resource "kubernetes_manifest" "eck-elasticsearch" {
  depends_on = [kubectl_manifest.eck-elastic-superuser]
  manifest = yamldecode(templatefile("../scripts/eck/eck-elasticsearch.yaml", {
    namespace = kubernetes_namespace.observability.metadata[0].name
  }))

  field_manager {
    force_conflicts = true
  }
}
```

```yaml
# ../scripts/eck/eck-elastic-superuser.yaml

apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-es-elastic-user # <CRD Elasticsearch Name>-es-elastic-user
  namespace: ${namespace}
data:
  elastic: ${base64encode(password)}
```

```yaml
# ../scripts/eck/eck-elasticsearch.yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: ${namespace}
spec:
  version: 8.8.2
  auth:
    fileRealm:
      - secretName: elastic-filebeat-ingestion-user
    roles:
      - secretName: elastic-filebeat-ingestion-role
  nodeSets:
    - name: master
      count: 1
      config:
        node:
          roles:
            - master
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp3
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 100m
                  memory: 2000Mi
                limits:
                  cpu: 500m
                  memory: 2500Mi
    - name: data
      count: 1
      config:
        node:
          roles:
            - data
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # Do not change this name unless you set up a volume mount for the data path.
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 10Gi
            storageClassName: gp3
      podTemplate:
        spec:
          nodeSelector:
            workload-type: observability
          containers:
            - name: elasticsearch
              resources:
                requests:
                  cpu: 100m
                  memory: 2Gi
                limits:
                  cpu: 500m
                  memory: 2Gi
```
### References
- https://registry.terraform.io/providers/cpanato/kubectl/latest/docs/resources/kubectl_manifest#apply_only

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
