### ISSUE TITLE
add `ValidatingAdmissionPolicy` resource from k8s `v1.28.0`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2250]
### Description

https://kubernetes.io/blog/2023/08/15/kubernetes-v1-28-release/#validatingadmissionpolicies-graduate-to-beta
https://kubernetes.io/docs/reference/access-authn-authz/validating-admission-policy/

with `ValidatingAdmissionPolicy` being moved to the beta state in `v1.28.0` we should consider whether this resource should be a high priority or wait until it has reached the stable state.

### YAML configuration

```yaml
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingAdmissionPolicy
metadata:
  name: "demo-policy.example.com"
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments"]
  validations:
    - expression: "object.spec.replicas <= 5"
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
