### ISSUE TITLE
GCP GKE manage FQDN network policy

### ISSUE THREAD

**Issue by SehiiRohoza** [hashicorp/terraform-provider-kubernetes#2342]
### Description

GKE clusters can enable L7 (FQDN) network policies for Dataplane v2 clusters (enabled for all new GKE Autopilot clusters by default). This is documented here:
https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies

I believe it is not currently possible to manage FQDN policy from within Terraform. This is documented here:
https://cloud.google.com/kubernetes-engine/docs/how-to/fqdn-network-policies#create-fqdn-network-policy

```
apiVersion: networking.gke.io/v1alpha1
kind: FQDNNetworkPolicy
metadata:
  name: allow-out-fqdnnp
spec:
  podSelector:
    matchLabels:
      app: curl-client
  egress:
  - matches:
    - pattern: "*.yourdomain.com"
    - name: "www.google.com"
    ports:
    - protocol: "TCP"
      port: 443
 ```

### Potential Terraform Configuration

```
resource "kubernetes_fqdn_network_policy_v1alpha1" "allow_out_fqdnnp" {
  metadata {
    name      = "allow-out-fqdnnp"
  }

  spec {
    pod_selector {
      match_labels = {
        "app" = "curl-client"
      }
    }

    egress {
      matches {
          pattern = "*.yourdomain.com"
      }
      matches {
          name = "www.google.com"
      }
      ports {
        port     = "443"
        protocol = "TCP"
      }
    }

    policy_types = ["Egress"]
  }
}
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
