### ISSUE TITLE
Pod Security Admission Controller

### ISSUE THREAD

**Issue by EmirDanfoss** [hashicorp/terraform-provider-kubernetes#2369]
### Description

As you may be aware, Pod Security Policy has been removed since Kubernetes version v.1.25, where Pod Security Admission took it's place. It should be put in consideration to implement Pod Security Admission Controller as a resource.

### References
https://kubernetes.io/docs/concepts/security/pod-security-admission/
https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/

### YAML configuration

``` YAML
apiVersion: apiserver.config.k8s.io/v1
kind: AdmissionConfiguration
plugins:
- name: PodSecurity
  configuration:
    apiVersion: pod-security.admission.config.k8s.io/v1
    kind: PodSecurityConfiguration
    defaults:
      enforce: "privileged"
      enforce-version: "latest"
      audit: "privileged"
      audit-version: "latest"
      warn: "privileged"
      warn-version: "latest"
    exemptions:
      usernames: []
      runtimeClasses: []
      namespaces: []
```
