### ISSUE TITLE
Annotations ending in kubernetes.io not being ignored

### ISSUE THREAD

**Issue by mersive-raypitmon** [hashicorp/terraform-provider-kubernetes#2411]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: v0.14.6
Kubernetes provider version: v2.25.2
Kubernetes version: v1.26.6-gke.1700
```
**Note:**  I just ran similar terraform against `Kubernetes version: v1.25.10-gke.2700` and I don't see the issue, so is this a k8s problem and not a provider issue?

### Affected Resource(s)
kubernetes_stateful_set

### Steps to Reproduce

`terraform plan`

### Expected Behavior
My STS resource should not show any changes.

### Actual Behavior
The output from the plan command states that it will null out a server-set annotation ending in `kubernetes.io`. The provider documentation states this:

> ! Note
> By default, the provider ignores any annotations whose key names end with kubernetes.io.
> ... 

It is not ignoring that annotation, as here is my output from `terraform plan`:
```
  # kubernetes_stateful_set.pgwatch2_sts will be updated in-place
  ~ resource "kubernetes_stateful_set" "my_sts" {
        id               = "default/mysts"
        # (1 unchanged attribute hidden)


      ~ spec {
            # (4 unchanged attributes hidden)


          ~ template {
              ~ metadata {
                  ~ annotations = {
                      - "kubectl.kubernetes.io/restartedAt" = "2023-06-14T14:48:46-06:00" -> null
                    }
                    # (2 unchanged attributes hidden)
                }

                # (1 unchanged block hidden)
            }

            # (2 unchanged blocks hidden)
        }
        # (1 unchanged block hidden)
    }
```
I've ran `terraform plan` on this bit of code several times over the past year, and I haven't noticed this until now. Also note that I am not manually setting any annotations in `spec.template.metadata.annotations`

I checked the actual YAML for the resource running in the GKE console and it does have the annotation:
```
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: myapp
  serviceName: myservice
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2023-06-14T14:48:46-06:00"
      creationTimestamp: null
      labels:
        app: myapp
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
