### ISSUE TITLE
kubernetes_manifest crashes on ArgoCD's ApplicationSet with matrix generator (git + cluster)

### ISSUE THREAD

**Issue by ivankorn** [hashicorp/terraform-provider-kubernetes#2580]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version:  v1.9.3
Kubernetes provider version: v2.30.0
Kubernetes version: 1.29.6-gke.1326000	
```

### Affected Resource(s)
- kubernetes_manifest
- opc_storage_volume

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "argocd_application_set" {
  manifest = provider::kubernetes::manifest_decode(file("argocd/application-set.yaml"))
}
```

### ApplicationSet Manifest (works with `kubectl create -f`) 
```
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-git
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - git:
              repoURL: https://github.com/<MASKED>/<MASKED>_kustomize ## WARN: real value is masked for privacy reasons
              revision: HEAD
              directories:
                - path: overlays/*/*
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
                  cluster-type: <MASKED> ## WARN: real value is masked for privacy reasons
  template:
    metadata:
      name: "{{.path.basename}}-{{.name}}"
    spec:
      project: "{{.name}}"
      source:
        repoURL: https://github.com/<MASKED>/<MASKED>_kustomize ## WARN: real value is masked for privacy reasons
        targetRevision: HEAD
        path: "overlays/{{.name}}/{{.path.basename}}"
      destination:
        name: "{{.name}}"
        namespace: <MASKED> ## WARN: real value is masked for privacy reasons
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        retry:
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
          limit: 5
        syncOptions:
          - CreateNamespace=true
```

### Debug Output
[debug.log](https://gist.github.com/ivankorn/ee1b9efe4ad64b99154c491c8d741788#file-debug-log)

### Panic Output
[crash.log](https://gist.github.com/ivankorn/ee1b9efe4ad64b99154c491c8d741788#file-crash-log)

### Steps to Reproduce
1. [install argocd](https://argo-cd.readthedocs.io/en/stable/operator-manual/installation/#core) e.g via helm https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
2. make `ApplicationSet` manifest as specified above
3. define `kubernetes_manifest` resource as specified above
4. `terraform init`
5. `terraform plan` or `terraform apply`

### Expected Behavior
No crash. Plan gets rendered or resource gets provisioned into Kubernetes.

### Actual Behavior
Both `terraform plan` and `tarraform apply` crash with the panic/debug output attached above

### Important Factoids
Non-matrix, f.e. `Cluster Generator` works fine. To the best of my knowledge the problem is reproducible only with  ArgoCD's Application Set with `Matrix Generator`. Other resources (both non-argocd and argocd) get provisioned just fine.

### References
- GH-2503

Note: My issue is slightly different because I'm using the new `provider::kubernetes::manifest_decode` provider function to define manifest. But I get very similar (or the same) error.
 
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
