### ISSUE TITLE
`kubectl apply` equivalent

### ISSUE THREAD

**Issue by KyleKotowick** [hashicorp/terraform-provider-kubernetes#2584]
## Terraform version, Kubernetes provider version and Kubernetes version
```
Terraform version: 1.9.5
Kubernetes Provider version: 2.32.0
Kubernetes version: 1.29.7
```

## Question

I need to apply some parameters to a namespace that I've created. With `kubectl`, I would do this as follows:
```
kubectl create ns mynamespace
kubectl apply -n mynamespace -f quota.yaml
```

Where `quota.yaml` is:
```
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quotas
spec:
  hard:
    pods: 5
  scopeSelector:
    matchExpressions:
    - operator: In
      scopeName: PriorityClass
      values:
      - myvalue1
      - myvalue2
```

Is there any way to achieve this same thing using the Terraform Kubernetes provider? I don't see any way to apply parameters like this in the [`kubernetes_namespace`](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs/resources/namespace) resource, and I don't see any other resource that would correspond to a `kubectl apply`.

Thanks!
