### ISSUE TITLE
Create kubernetes_persistent_volume_claim from snapshot

### ISSUE THREAD

**Issue by divomen** [hashicorp/terraform-provider-kubernetes#2608]
### Description

Currently kubernetes_persistent_volume_claim does not allow to specify data source.
This prevents us from using terraform to automate volume backups.

### Potential Terraform Configuration

```
resource "kubernetes_persistent_volume_claim" "default" {
  metadata {
    name = "my-pvc-clone"
  }
  spec {
    access_modes = ["ReadWriteOnce"]
    resources {
      requests = {
        storage = "1Gi"
      }
    }
    data_source {
      persistent_volume_claim {
        claim_name = "my-pvc-original"
      }
    }
  }
}
```

Сorresponding kubectl manifest

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc-clone
spec:
  dataSource:
    kind: PersistentVolumeClaim
    name: my-pvc-original
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

```
