### ISSUE TITLE
Apply fails when hpa metric type was changed in the cluster

### ISSUE THREAD

**Issue by shysank** [hashicorp/terraform-provider-kubernetes#2641]
### Terraform Version, Provider Version and Kubernetes Version

```
Terraform version: 1.7.5
Kubernetes provider version: 2.31.0
Kubernetes version: 1.28
```

### Affected Resource(s)
- kuberenetes_manifest

### Terraform Configuration Files
```hcl
resource "kubernetes_manifest" "hpa" {
  manifest        = yamldecode(file("path_to_hpa"))
  field_manager {
    force_conflicts = true
  }
}

```

### Steps to Reproduce
1. Add a kuberetnes hpa manifest with cpu metric as a kuberetes_manifest resource
Eg. 
```
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
...
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: 80
          type: Utilization 
```
3. Update the hpa directly in the cluster using `kubectl edit` to something like (note: `target:`) 
```
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          averageValue: 100m
          type: AverageValue 
```
4. terraform apply

### Expected Behavior
It should override the hpa with the configured spec in kuberenetes_manifest resource
### Actual Behavior
Apply failed with the following error
```
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to
│ module.service.kubernetes_manifest.service_components["autoscale.yaml"],
│ provider "provider[\"registry.terraform.io/hashicorp/kubernetes\"]"
│ produced an unexpected new value:
│ .object.spec.metrics[1].resource.target.type: was
│ cty.StringVal("Utilization"), but now cty.StringVal("AverageValue").
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker
```
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
