### ISSUE TITLE
support `groupsnapshot.storage.k8s.io/v1beta1`

### ISSUE THREAD

**Issue by BBBmau** [hashicorp/terraform-provider-kubernetes#2678]
### Description

`v1.32` graduated `groupsnapshot.storage.k8s.io` from `alpha` -> `beta`

It introduces:
- VolumeGroupSnapshot
- VolumeGroupSnapshotClass

More info can be found here that goes over the usage: https://kubernetes.io/blog/2024/12/18/kubernetes-1-32-volume-group-snapshot-beta/

## YAMLs

`VolumeGroupSnapshot`:
```yaml
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshot
metadata:
  name: snapshot-daily-20241217
  namespace: demo-namespace
spec:
  volumeGroupSnapshotClassName: csi-groupSnapclass
  source:
    selector:
      matchLabels:
        group: myGroup

```
`VolumeGroupSnapshotClass`:
```yaml
apiVersion: groupsnapshot.storage.k8s.io/v1beta1
kind: VolumeGroupSnapshotClass
metadata:
  name: csi-groupSnapclass
  annotations:
    kubernetes.io/description: "Example group snapshot class"
driver: example.csi.k8s.io
deletionPolicy: Delete
```

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment
