### ISSUE TITLE
Feature Request: Container Storage Interface Support for Persistent Volumes

### ISSUE THREAD

**Issue by myyra** [hashicorp/terraform-provider-kubernetes#296]
[Container Storage Interface (CSI) has been promoted to GA in the Kubernetes v1.13 release](https://kubernetes.io/blog/2019/01/15/container-storage-interface-ga/). This would add support for multiple cloud providers/custom solutions with one spec.

[The API](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#csipersistentvolumesource-v1-core) is relatively simple since most of the work is handled by the external driver.

**Comment by ipnextgen** [comment]
As this is the new recommend way to use AWS EFS with EKS. Would like to use it via terraform.

`apiVersion: storage.k8s.io/v1beta1
kind: CSIDriver
metadata:
  name: efs.csi.aws.com
spec:
  attachRequired: false`

ref: https://github.com/kubernetes-sigs/aws-efs-csi-driver/blob/master/deploy/kubernetes/base/csidriver.yaml

**Comment by msnelling** [comment]
Supporting CSI is the only way AFAIK that we can use terraform with Longhorn volumes.
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-vol-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '3'
      staleReplicaTimeout: '2880'
    volumeHandle: existing-longhorn-volume
```
