### ISSUE TITLE
Feature Request: PersistentVolume spec.nfs key

### ISSUE THREAD

**Issue by matti** [hashicorp/terraform-provider-kubernetes#317]
```
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileserver
spec:
  ...
  nfs:
    path: /default
    server: 10.210.81.66
```

currently `nfs` is unknown key
