### ISSUE TITLE
kubernetes_deployment: changing strategy to Recreate from Rolling breaks the update

### ISSUE THREAD

**Issue by josmo** [hashicorp/terraform-provider-kubernetes#585]
### Affected Resource(s)
Please list the resources as a list, for example:
- kubernetes_deployment

### Terraform Configuration Files
Updated to
```hcl
resource "kubernetes_deployment" "blah" {
  spec {
    strategy {
      type = "Recreate"
    }
  }
}
```

### Expected Behavior
Expect it to recreate the deployment or unset the rolling_update defaults on the strategy

### Actual Behavior
If it was not set or set to RollingUpdates then the rolling_update defaults stay behind and gives an spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a deployment with default strategy
2. change the strategy to "Recreate"
3. Watch it error out :)

### Important Factoids
I imagine the easy fix is to force new for the resource,  but the better fix is to unsetting rolling_update when type is set to Recreate.

**Comment by yzargari** [comment]
I have the same issue with provider version 1.9.0

**Comment by software-opal** [comment]
Likewise in 1.10.0 and terraform 0.12.12

**Comment by alexsomesan** [comment]
This same issue happens with `kubectl` as seen below:
```
~/test-dep » kubectl apply -f testdep.yaml                                                                                                                                                    alex@alex-macbook
deployment.apps/test-dep created
------------------------------------------------------------
~/test-dep » cat testdep.yaml                                                                                                                                                                 alex@alex-macbook
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-dep
  name: test-dep
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-dep
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: Recreate
  template:
    metadata:
      labels:
        app: test-dep
    spec:
      containers:
      - image: nginx
        name: nginx
------------------------------------------------------------
~/test-dep » kubectl apply -f testdep.yaml                                                                                                                                                    alex@alex-macbook
The Deployment "test-dep" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```

Furthermore, Terraform doesn't have the ability to do cross-attribute validation which would be the only mechanism that could detect this condition. Unlikely that we can fix this on the provider side.
