### ISSUE TITLE
NOT support BackendConfig ??

### ISSUE THREAD

**Issue by OrangePieiep** [hashicorp/terraform-provider-kubernetes#764]
Hi there,

Does k8s provider support BackendConfig ? If, Is there any alternative way?  

https://cloud.google.com/kubernetes-engine/docs/concepts/backendconfig
How to translate the following yaml to HCL ?

```yaml
apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: my-policy
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-iap-secret
```
