### ISSUE TITLE
Feature: GlobalNetworkPolicy (or custom YAML)

### ISSUE THREAD

**Issue by hazcod** [hashicorp/terraform-provider-kubernetes#774]
### Terraform Version
Latest on 24/02/2020

### Affected Resource(s)
- kubernetes_network_policy

### Expected Behavior
A terraform resource equivalent for the following:
```yaml
apiVersion: crd.projectcalico.org/v1
kind: GlobalNetworkPolicy
metadata:
  name: deny-icmp-kube-02
spec:
  selector: "role == 'k8s-node'"
  order: 0
  ingress:
  - action: Allow
    protocol: ICMP
  egress:
  - action: Allow
    protocol: ICMP
```

### Actual Behavior
Only `kubernetes_network_policy` which is per-namespace, nothing global.
