### ISSUE TITLE
config_context ignored in provider

### ISSUE THREAD

**Issue by rmgpinto** [hashicorp/terraform-provider-kubernetes#813]
### Terraform Version and Provider Version

Terraform v0.12.20

### Affected Resource(s)

`provider kubernetes 1.11.1`

### Terraform Configuration Files
```hcl
provider "kubernetes" {
  config_context = "dev"
}
```

### Expected Behavior
I expect the provider to use the `config_context` passed as argument.

### Actual Behavior
The provider is using the config context defined in the `~./kube/config`.

### Steps to Reproduce
`terraform plan`

**Comment by sebolabs** [comment]
does that `dev` context exist in `~./kube/config` ?

**Comment by rmgpinto** [comment]
Yes it exists.

**Comment by aareet** [comment]
@rmgpinto can you check the value of `KUBE_CTX` if this is still reproducible?

**Comment by aareet** [comment]
Closing since it has been a few weeks, please reopen if this is still an issue.

**Comment by Djabx** [comment]
I've the same issue:

# My Terraform

```terraform
resource "null_resource" "cluster" {
  provisioner "local-exec" {
    command = "gcloud container clusters get-credentials ${local.cluster_name} --project=${local.project_id} --zone=${local.zones[0]}"
  }
}

provider "kubernetes" {
  config_context  = "gke_${local.project_id}_${local.zones[0]}_${local.cluster_name}"
  load_config_file       = false

  alias = "ops-cluster-dev"
}
```

# Kubeconfig 

After the apply I've my kube config change like this:

```yaml
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://1.1.1.1
  name: gke_project_europe-west1-b_cluster-name
[...]
- name: gke_project_europe-west1-b_cluster-name
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib64/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

# Terraform Apply

But when I do my `terraform apply` I've got this output:

```shell
Error: Post "http://localhost/api/v1/namespaces/default/serviceaccounts": dial tcp [::1]:80: connect: connection refused
```

The URL does not seem to be changed.

# Versions

Terraform: 0.12.29
+ provider.google v3.40.0
+ provider.google-beta v3.40.0
+ provider.kubernetes v1.13.2
