### ISSUE TITLE
Add support of sub_path_expr for container volume_mount

### ISSUE THREAD

**Issue by benjah1** [hashicorp/terraform-provider-kubernetes#920]
### Description

Add support of sub_path_expr for container volume_mount

subPathExpr was added the VolumeMount since 1.15 as beta. It because stable since 1.17. 
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#volumemount-v1-core
https://kubernetes.io/docs/concepts/storage/volumes/#using-subpath-with-expanded-environment-variables

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by benjah1** [comment]
I found a work around. by using `kubectl patch`.

in the sts.tf
```
resource "kubernetes_stateful_set" "prometheus" {
  ...
          volume_mount {
            name             = "data"
            mount_path       = "/data"
            //sub_path_expr  = "$(POD_NAME)"
          }
  ...
  provisioner "local-exec" {
    command = "kubectl -n ${var.namespace} patch sts prometheus --patch \"$(cat ${path.module}/patch/subpathexpr.yaml)\""
  }
}
```

in the patch/subpathexpr.yaml
```
spec:
  template:
    spec:
      containers:
        - name: prometheus
          volumeMounts:
            - mountPath: "/data"
              subPathExpr: $(POD_NAME)
```
