### ISSUE TITLE
kubernetes_job "No configuration has been provided"

### ISSUE THREAD

**Issue by rafabordon** [hashicorp/terraform-provider-kubernetes#946]
### Terraform Version and Provider Version
Terraform v0.11.14
+ provider.aws v2.70.0
+ provider.kubernetes v1.12.0

### Affected Resource(s)
- kubernetes_job

### Terraform Configuration Files
```
# Locals
locals {
    labels = "${map(
                    "helm.sh/chart", "ingress-nginx-2.9.0",
                    "app.kubernetes.io/name", "ingress-nginx",
                    "app.kubernetes.io/instance", "ingress-nginx",
                    "app.kubernetes.io/version","0.33.0",
                    "app.kubernetes.io/managed-by", "Helm")}"
    controller_labels = "${merge( 
                                local.labels,
                                map("app.kubernetes.io/component", "controller")
                        )}"
    admission_labels = "${merge(
                            local.labels,
                            map("app.kubernetes.io/component","admission-webhook"))}"
    create_args = "${list("create","--namespace=ingress-nginx", "--secret-name=ingress-nginx-admission", "--host=ingress-nginx-controller-admission,ingress-nginx-controller-admission.ingress-nginx.svc")}"
}

# Job Admission Create
resource "kubernetes_job" "ingress-nginx-admission-create" {
    metadata {
        name = "ingress-nginx-admission-create"
        namespace = "${kubernetes_namespace.ingress-nginx.metadata.0.name}"
        labels = "${local.admission_labels}"
        annotations = {
            "helm.sh/hook" = "pre-install,pre-upgrade"
            "helm.sh/hook-delete-policy" = "before-hook-creation,hook-succeeded"
        }
    }

    spec {
        template {
            metadata {
                name = "ingress-nginx-admission-create"
                labels = "${local.admission_labels}"
            }
            spec {
                container {
                    name    = "create"
                    image   = "docker.io/jettech/kube-webhook-certgen:v1.2.0"
                    image_pull_policy = "IfNotPresent"
                    args = "${local.create_args}"
                }
                restart_policy = "OnFailure"
                service_account_name = "${kubernetes_service_account.ingress-nginx-admission.metadata.0.name}"
                security_context = {
                    "run_as_non_root" = true
                    "run_as_user" = 2000
                }
            }
        }
        backoff_limit = 10
    }
}
```

### Debug Output
https://gist.github.com/rafabordon/362341814fcad151b9fc0ebf2e161342

### Expected Behavior
It should have created a new job. If I deploy the object from a exact YAML version the jobs is created without any inconvienience:
```
apiVersion: batch/v1
kind: Job
metadata:
  name: ingress-nginx-admission-create
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    helm.sh/chart: ingress-nginx-2.9.0
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/version: 0.33.0
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: admission-webhook
  namespace: ingress-nginx
spec:
  template:
    metadata:
      name: ingress-nginx-admission-create
      labels:
        helm.sh/chart: ingress-nginx-2.9.0
        app.kubernetes.io/name: ingress-nginx
        app.kubernetes.io/instance: ingress-nginx
        app.kubernetes.io/version: 0.33.0
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: admission-webhook
    spec:
      containers:
        - name: create
          image: docker.io/jettech/kube-webhook-certgen:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=ingress-nginx-controller-admission,ingress-nginx-controller-admission.ingress-nginx.svc
            - --namespace=ingress-nginx
            - --secret-name=ingress-nginx-admission
      restartPolicy: OnFailure
      serviceAccountName: ingress-nginx-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
```

### Actual Behavior
Terraform reports the job was successfully created. However I get this message on the job logs view in the cluster dashboard.
```{"error":"invalid configuration: no configuration has been provided","level":"fatal","msg":"error building kubernetes config","source":"k8s/k8s.go:20","time":"2020-08-06T17:47:07Z"}```

### Steps to Reproduce
This code should create an Nginx Ingress Controller in AWS. https://gist.github.com/rafabordon/a1b2def2e79685f9e94dca901f2ef251

1. `terraform apply` -->

### Important Factoids
I have superadmin permissions in the AWS account. Running against an EKS cluster also created with Terraform.
