### ISSUE TITLE
incompatibility between yaml, kubernetes_secret and Jenkins Kubernetes Credential Provider

### ISSUE THREAD

**Issue by shintasmith** [hashicorp/terraform-provider-kubernetes#995]
The following yaml file, when loaded using `kubectl create -f <yaml>` , will show up fine as Jenkins credentials of type Certificate:
```

kind: Secret
metadata:
  # this is the jenkins id.
  name: "another-test-certificate"
  labels:
    # so we know what type it is.
    "jenkins.io/credentials-type": "certificate"
  annotations:
    # description - can not be a label as spaces are not allowed
    "jenkins.io/credentials-description" : "certificate credential from Kubernetes"
type: Opaque
data:
  password: "bXlwYXNzd29yZA=="
  # PKCS#12 base64 encoded bytes
  certificate: MIIKQQIBAzCCCg********==
```
The command `kubectl describe secret another-test-certificate` shows this:
```
Name:         another-test-certificate
Namespace:    mynamespace
Labels:       jenkins.io/credentials-type=certificate
Annotations:  jenkins.io/credentials-description: certificate credential from Kubernetes

Type:  Opaque

Data
====
certificate:  2629 bytes
password:     10 bytes
```
Jenkins Kubernetes Credentials Provider plugin displays/loads this secret successfully in Jenkins Credentials UI.

However, when translating that yaml to Terraform `kubernetes_secret` like this:
```
resource "kubernetes_secret" "test-certificate-credz" {
  metadata {
    name = "test-certificate-credz"
    namespace = var.namespace
    labels = {
      "jenkins.io/credentials-type" = "certificate"
    }
    annotations = {
      "jenkins.io/credentials-description" = "test certificate credentials"
    }
  }

  data = {
    password = "mypassword"
    certificate = "${filebase64("${path.module}/files/test_certificate.pfx")}"
  }

  type = "Opaque"
}
```
I have to use the clear text (raw) version in the `data` field for the password. Otherwise, if I pass in the encoded version of the password, the password will be double-encoded. 

While I can specify a clear text (raw) version of the password, I can't specify the raw version the certificate because it's binary. If I base64 encode it like the above, the resulting field will be double-encoded. The reader of these secrets are the [Jenkins Kubernetes Credentials Provider](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/) . Examples of the Certificate yaml is shown in this [examples](https://jenkinsci.github.io/kubernetes-credentials-provider-plugin/examples/) page.

Is it possible to have the `data` field in `kubernetes_secret` consistent with the `data` field in yaml file? I.e: it takes base64 encoded version of the data?

I am unable to use Terraform `kubernetes_secret` to load up Certificate secrets that are readable by the Jenkins plugin, because of this inconsistency.
